### ISSUE TITLE
[core] create (or find) an Image component that uses web workers and lazy loads

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1010]
My gut tells me that we'll want to roll our own React component, but if you can find an existing stable library that does these things and has an easy API, I'm open to that as well.

**Comment by palamago** [comment]
I realized that we use `background-image` for tiles so, I created a small component that use Observer ( https://github.com/researchgate/react-intersection-observer ) and set the bg if is in the viewport. Good start. 
Taking a look into web worker part now.
