### ISSUE TITLE
[cms] ability to duplicate formatters

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1040]
<img width="501" alt="Screen Shot 2020-06-23 at 4 01 53 PM" src="https://user-images.githubusercontent.com/1847581/85454462-f7656680-b56a-11ea-9fa8-9b22f33a7e14.png">

**Comment by jhmullen** [comment]
This functionality is not written yet. I am removing the button in Pull Request #1043 and will revisit adding this functionality later. For now, moving this to Backlog.
