### ISSUE TITLE
[cms] internal titles for visualizations

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1041]
Similar to generators, it's sometimes nice for a non-user facing title that only CMS editors can see. This was brought up by the CDC-ARPSP team, but I could also see it useful for OEC editors as their juggling a few vizzes in each section with a bunch of different "allowed" flags.

**Comment by jhmullen** [comment]
This would be breaking, and should be done in a full viz overhaul, which is handled here:  #1216
