### ISSUE TITLE
[vizbuilder] topojsonId should allow Function type

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1053]
The `topojsonId` accessor method [in d3plus](https://github.com/d3plus/d3plus-geomap/blob/master/src/Geomap.js#L655) accepts both Arrays or Functions. This message is displayed in the browser console:

<img width="942" alt="Screen Shot 2020-07-03 at 11 13 07 AM" src="https://user-images.githubusercontent.com/1847581/86481727-908c3e00-bd1e-11ea-9c84-5cb71def8893.png">

I'm using `v0.3.9`, but I'm okay with only fixing this in v4.

**Comment by frabarz** [comment]
This is just a `prop-types` complaint, the properties are passed directly and should work normally. I'll patch the accepted prop types.

**Comment by davelandry** [comment]
Closing all `[vizbuilder]` issues, as the canon-vizbuilder package is no longer in development in favor of the more generic https://github.com/datawheel/vizbuilder package
