### ISSUE TITLE
[cms] button to save profile as PDF

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1070]
This will include:
- [x] setting up a print-version of the Profile component (maybe a query arg? `?print=true`)
- [x] an API route that uses puppeteer to take a screenshot of said print-version of the Profile (including all vizzes)
- [x] extracting every data URL from each viz and displaying it in tables at the end of the printable page
- [x] adding a "Save as PDF" button into the Hero section component
- [x] rendering stat tooltip text underneath the stat
- [x] boolean flag on whether content should be "allowed" (maybe instead of a new column, this could just be 2 new magic variables? `isPrint` and `isBrowser`?)

**Comment by jhmullen** [comment]
For reference, the tooltip printing is handled here: https://github.com/DeloitteGeospatial/cdc-pha/pull/1053
