### ISSUE TITLE
[cms] document sandbox setup steps for Debian and CentOS

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1100]
This commit disables sandboxing, which is a _potential_ security flaw: https://github.com/Datawheel/canon/commit/76457b4b206fd23569c62385f9ff95384435d235

I say "potential", because the pdfRoute only ever hits it's own hostname, so theoretically external off-server code can't be executed. That being said, let's figure out the secure way to set up sandboxing correctly for Debian (most Datawheel projects) and CentOS (CDC AR&PSP), starting off of Puppeteer's basic troubleshooting (I tried the first solution for in CentOS, and I couldn't get it working quickly):  https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

**Comment by jhmullen** [comment]
https://github.com/Datawheel/canon/tree/master/packages/cms#enable-namespaces-centos
