### ISSUE TITLE
[cms] profileSearch endpoint keywords not working

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1101]
In the CDC AR&PSP, the "United States" search member has a keyword of "stewardship" defined in the CMS (and confirmed in the database), but when hitting the following URL, nothing is returned: https://cdc-earwig.datawheel.us/api/profilesearch?query=stewardship&limit=10

**Comment by jhmullen** [comment]
@davelandry The keywords are working properly, but there are two issues going on here:

- In the case of `stewardship`, there is a leading space before the word which is causing the matching not to work. I will add code to remove leading and trailing spaces.
- In the case of almost ALL the other keywords, they have been entered into the keywords table using literal quotation marks, for example, `"hai progress"`. This means the user would need to type this entire phrase, *including the quotation marks* for this to be a match. I will add code to remove quotation marks as well, I would argue that special characters don't belong in plaintext keywords.

I admit the current state of this is "easy to mess up," I will put a few more guard rails in, as mentioned:
- [] remove leading/trailing spaces
- [] deny quotation marks from being typed

However, for right now, this can be fixed live on earwig by removing quotation marks and ensuring that there are NO spaces between the comma separated values. 

Further, I'd suggest that keywords in general are split by commas, there are some pretty long phrases here, which won't match unless fully typed. Therefore things like: `cephalosporin resistant pseudomonas aeruginosa` should really be more like: `cephalosporin,resistant,pseudomonas,aeruginosa` (no quotes, no spaces, comma separated for parsing)

**Comment by jhmullen** [comment]
For posterity, I've changed the psql `overlap` function that was used for keywords, which required an exact match.

It's a bit of antipattern, but I now varchar cast the keywords array and just do a `%LIKE%` on that joined string, which allows for substring matches and "fuzzier" matching in general (the overlap function had trouble with special characters).
