### ISSUE TITLE
[cms] restrict &slugs lookup by cubename

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#1130]
slug injection doesn't currently restrict by cubename, add this.

**Comment by AlanORB** [comment]
![github issue](https://user-images.githubusercontent.com/54365586/98380515-709bbc80-2027-11eb-8164-1bf26102fe03.jpg)

the thing is that I noticed that when you use a magic variable, the slug injecction doesnt work, for example, in the first image, you explicity put &slugs=HS Product:Product and it works, but when using a magic variable such as <depthProduct> it doesnt work

**Comment by jhmullen** [comment]
Interesting observation, I hadn't thought that `<vars>` would be used for the accessor here. I will add this in the same PR.
