### ISSUE TITLE
[vizbuilder] all cubes are listed in the cube selector dropdown

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1148]
Latest is deployed here: https://lapis.datausa.io/visualize?measure=226bN8&groups%5B0%5D=Z19J7ox%7C0&time=2017

<img width="1260" alt="Screen Shot 2020-12-08 at 7 11 46 PM" src="https://user-images.githubusercontent.com/1847581/101556592-39535f00-3989-11eb-894d-33107b2c1263.png">

**Comment by frabarz** [comment]
I can't reproduce the issue, can your detail the steps you followed to get there?
![image](https://user-images.githubusercontent.com/11713191/101913773-34b5c300-3ba2-11eb-9d1f-213eda57cefe.png)

**Comment by davelandry** [comment]
@frabarz sorry, my bad, I posted the wrong link. Looks like it's only doing it for certain measures?
https://lapis.datausa.io/visualize?measure=Z1LxWvG&groups%5B0%5D=Z1tpPKe%7C0&groups%5B1%5D=2pvOai%7C0%7C1400&time=2017
