### ISSUE TITLE
[cms] Make populateSearch give feedback to end user

### ISSUE THREAD

**Issue by palamago** [Datawheel/canon#1176]
During dev stage populateSearch is used very often and sometimes it fails silently giving no feedback to the editor. It would be great to provide a response to end user to understand the error better directly from cms view.

Identified unhandled exceptions that could block the execution:
- A problem with duplicate ids on a dimension.
- Wrong measure set in metadata -let say any query to cubes that fail for some reason-.

**Comment by jhmullen** [comment]
@palamago This will be part of a larger canon-wide assessment of error-reporting. Right now, a template for how this could work can be found in the translation code, which does a pretty good job of bubbling up server-side errors. I'm interested in potentially having a middleware that wraps all cms api endpoints to unify the error structure.

My order of operations here will be to attack this first, then look at the similarities between translation and this effort, and unify that into a framework.

**Comment by jhmullen** [comment]
Error-reporting overhaul is moving to reports.
