### ISSUE TITLE
[core] share cookies between subdomains

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/canon#119]
Helpful for sites (like codelife) which depend on logins across subdomains: https://github.com/jaredhanson/passport/issues/125

**Comment by davelandry** [comment]
I tried to implement this using the `domain` key as stated in that issue, but I couldn't get it working. This will need a deeper dive.

**Comment by davelandry** [comment]
After digging into this with @jhmullen, our current hypothesis is that switching to a server managed session library like [express-session](https://www.npmjs.com/package/express-session) might be the solution.
