### ISSUE TITLE
implement code splitting of dependencies

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#12]

**Comment by jazzido** [comment]
Bumping this up. The Datachile code bundle is getting dangerously big; we'd benefit a lot from this feature.

Maybe take a look at how the Zeit guys are doing it? https://github.com/zeit/next.js/#automatic-code-splitting

**Comment by davelandry** [comment]
@frabarz could you take a look into this issue? the idea is that the `app.js` file should be split into multiple files, one for each route of a project. I've found this great library [here](https://github.com/jamiebuilds/react-loadable) that looks like it could work pretty easily with our setup. The only unknown is how we can apply that to all user-defined routes.

**Comment by frabarz** [comment]
I have been investigating and, in the current state of webpack + canon, we can apply a stable code splitting using making the following change on the react-router components:

Current implementation:
```jsx
import Component from "path/to/Component";
...
<Route path="route/to/component" component={Component} />
```

New implementation:
```jsx
<Route 
  path="route/to/component"
  getComponent={(location, cb) =>
    import("./path/to/Component").then(module => cb(null, module.default))
  }
/>
```
I tested this configuration with DataChile and CNYVitals, and both compiled and worked successfully. However, the files generated using this approach don't meet the purpose; there's still a big `main.js` file and lots of small `<number>.js` loaded per route. This big main.js, of around 3MB unzipped, preloads most of the vendor code, which is what makes most of the code in the site; while the smaller route files, of no more than 300KB, contain some duplicated vendor code + the components themselves.

Considering this, a better approach to code splitting would be identifying some big groups of vendor code, like `lodash` and `d3plus-react`, and try to chunk them from the main vendor code. This would have to be done in a per-project basis.

**Comment by davelandry** [comment]
Thanks for the explanation and research @frabarz. We should still move forward with this code-splitting, as there will still be improvements in some of the other sites (I'm thinking of CodeLife, where d3plus is ONLY used in the admin panel).

Is there any way we can somehow allow canon users to still write a simplified route? Maybe we make our own `CanonRoute` component that extends `Route`, and simply takes `path` and `component` props, and if the `component` prop is a string we implement this `getComponent` logic? Could you take a first stab at that @frabarz?

**Comment by jhmullen** [comment]
Is code-splitting implemented, can this be closed?

**Comment by davelandry** [comment]
Code-splitting works, just not with SSR required pages. (ie. we split out CMS code, but can't do it with profiles)
