### ISSUE TITLE
[core] recover from broken DB connection

### ISSUE THREAD

**Issue by jspeis** [Datawheel/canon#121]
I noticed an issue with the CNY site where it appeared based on logs the postgres server became temporarily unavailable at one point, but then became available again. Based on the logs it seems like sequelize was still returning errors even after the connectivity to the database recovered so when users would try to login it seems like there would be still be sequelize errors, because the initial connection had been broken. This is what I think had happen, so wanted to check if the initial connection to the DB is broken is canon able to recover without a restart?

**Comment by davelandry** [comment]
> non-answer but acknowledging the question: 

I could see that being the case, but I really don't know for sure

**Comment by jspeis** [comment]
bump (for data usa)

**Comment by davelandry** [comment]
Found this thread here, where the issue was supposedly handled in sequelize but seems to not work for some people: https://github.com/sequelize/sequelize/issues/2113

@jspeis have you encountered this with the new Data USA, or just planning "just in case" for the future?
