### ISSUE TITLE
[core] HardSourceWebpackPlugin prevents the update of environment variables

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#123]
In the datachile dev environment we need to change constantly the URL for the `CANON_CONST_API` environment variable, to test production issues and new cubes in localhost. However the webpack plugin caches the value of the envvar at the moment it makes a initial caching, and changing the value after that has no effect on the development build.

For now the only way to solve this is clearing the cache, running

```
rm -rf node_modules/datawheel-canon/src/node_modules/.cache/*
```

**Comment by davelandry** [comment]
this would be great to expose as a global canon script, maybe `canon-clear`?

**Comment by frabarz** [comment]
I actually saved it as a script in vizbuilder's package.json, it was useful to solve a small problem I had before.
It would probably be useful along with other kinds of clearing in future use.

**Comment by davelandry** [comment]
with the latest release, the cache directory is now always stored here: `node_modules/.cache/`
