### ISSUE TITLE
emit css/postcss errors when running `npm run dev`

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#124]
Currently, css errors (like using a mixin in a file and forgetting to include `mixins.css`, lulz) are only printed when running `npm run build`. This causes the build to fail silently when (re)running `npm run dev`. 

NOTE: if the server is currently running and encounters a css error, the server typically keeps running and injecting the css as if nothing is wrong.

**Comment by perpetualgrimace** [comment]
Update: found a case in datachile where the error was not printed even when running `npm run build`

**Comment by davelandry** [comment]
@perpetualgrimace can you give me some clarification on this? In my test repo, if I add an undefined mixin without importing the file that contains it:

```css
.image {
  @mixin icon twitter {
    background: url(twt.png);
  }
}
```

It does show me an error in my Terminal... am I misunderstanding?
