### ISSUE TITLE
[vizbuilder] remove chart name from viz titles

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#125]
example: "Barchart of Average Age by Nation" should just be "Average Age by Nation"

**Comment by frabarz** [comment]
This would make all the charts have the same title
Should I show it in the extended chart mode only, or always show it?

**Comment by davelandry** [comment]
That's a very good point...

Only show it in extended mode!

**Comment by frabarz** [comment]
after testing the last commit, not all the charts have the same title: line plot, stacked area, and barchart for years use Year in the X axis
![image](https://user-images.githubusercontent.com/11713191/44113473-909d69b4-9fde-11e8-81fa-d0a51f2023bf.png)

what do you think about showing the title only if none of these three cases are visible?

**Comment by davelandry** [comment]
ahh ok, in that case, I think it would be best to show all titles (even if there are duplicates)

**Comment by frabarz** [comment]
in that case, this issue is ready, I will send the PR
