### ISSUE TITLE
[cms] unable to reorder items immediately after disabled items

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#1267]
In this example from Data USA, the reorder button that is placed on/after disabled stats is unclickable, causing any stats after it to not be able to be reordered in front of it.

<img width="787" alt="Screen Shot 2021-10-08 at 3 58 20 PM" src="https://user-images.githubusercontent.com/1847581/136618222-39784a3f-a7a9-46e5-9919-d06d3cd8129f.png">

Probably just a z-index issue, but not sure if this problem might go away entirely with the new section-first interface. My current workaround is to temporarily enable the stat, do the reordering, and then re-apply the disabled state.

**Comment by jhmullen** [comment]
The workaround should suffice here, and this won't be a problem in canon-reports
