### ISSUE TITLE
[core] enable aliases in CSS @import

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#1283]
Currently the aliases `$app` and `$root` are available when using `import` in javascript, but don't work in `@import` declarations in CSS files.

**Comment by jhmullen** [comment]
@frabarz Could you set a priority on this issue? @davelandry Would this be difficult to add?

**Comment by davelandry** [comment]
@jhmullen I've never done this before, but I would guess that it's just a simple webpack setting ¯\_(ツ)_/¯
