### ISSUE TITLE
[vizbuilder] apply tickFormat to yConfig

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#133]
By default, this should use the `formatAbbreviate` function exported from `d3plus-format`, and if the measure's `"units_of_measurement"` is set to "Dollars", then add a dollar sign before the value

**Comment by frabarz** [comment]
Considering the variations in the way of formatting currency, and possibly others, should we leave part of this config to the user? as in, setting a new attribute or config default, or using another annotation

**Comment by davelandry** [comment]
@frabarz how about something like a `formatting` prop, where you provide different formatter functions based on the `units_of_measurement`, so we would do something like this here:

```jsx
<Vizbuilder 
  formatting={{
    Dollars: d => `$${formatAbbreviate(d)}`
  }} 
  ... 
  />
```
