### ISSUE TITLE
[reports] Style inline generators

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#1335]
In cms-1.0-develop, one can click a generator in VariablesList, and the entire modal will replace its contents with the generator the user clicked. They can edit this, then click "Save & Return" at which point the modal returns to the statlike.

Dave, can you style this such that:
- [x] The hover is conditional over only generators
- [x] The hover is somehow meaningful for clicking (use a tooltip to explain?)
- [x] The transition of going from the normal editor to the `setInlineId` editors has some kind of visually helpful slide/transition
- [x] Any other design elements that would help the user understand "where we are"

**Comment by davelandry** [comment]
VariableList is re-styled on my working branch `cms-1.0-inline-generator-css`:

<img width="1260" alt="Screen Shot 2022-01-25 at 6 23 46 PM" src="https://user-images.githubusercontent.com/1847581/151076518-f763fc52-70ea-42d4-bf6d-8fccf9e54532.png">
