### ISSUE TITLE
[vizbuilder] remove duplicate depth levels from selector

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#136]
Testing Opioid Overdoses on the Data USA cube:

<img width="290" alt="screen shot 2018-08-16 at 1 58 37 pm" src="https://user-images.githubusercontent.com/1847581/44225869-8da0f800-a15c-11e8-907f-591cb41c421e.png">

**Comment by frabarz** [comment]
Those repeated States correspond to levels "[Geography].[State].[State]" and "[Geography].[County].[State]".

Currently there's a name formatter function called `composePropertyName` which would make it look like this:
![image](https://user-images.githubusercontent.com/11713191/44296689-c2669980-a299-11e8-9ecb-0ce1b2b61be3.png)

There's also the subtitle in the selector. I think we made it like that before we added the dimension selector, so maybe it's a better option to use it for hierarchies, though it's more common level fullnames are [Dim].[LevelName].[LevelName], so in the selector it would just appear twice very often.

What do you think?

**Comment by davelandry** [comment]
@frabarz selecting `[Geography].[State].[State]` or `[Geography].[County].[State]` produces the same results, correct? If so, we should only be showing 1, because this nesting differentiation is only used in more advanced cases outside of this vizbuilder.

**Comment by davelandry** [comment]
Additionally, we need a catch to only show dimensions with shared hierarchy in the filter selector:

<img width="303" alt="screen shot 2018-08-21 at 12 14 41 pm" src="https://user-images.githubusercontent.com/1847581/44414498-f19c3580-a53b-11e8-9d87-af429d1cc931.png">

**Comment by davelandry** [comment]
As discussed in Slack:
1. if there are duplicate levels in the depth selector, only show the ones where the level matches the hierarchy (ie. `State.State` and `County.County`)
2. in the cut menu, only display the dimensions that share the same hierarchy (ie. if `County.County` is selected for group by, only show `County.State` and not `State.State` in the cut menu)

**Comment by cnavarreteliz** [comment]
I reopened this issue because there's a weird behavior using measure of `county_health_ranking` cube.
