### ISSUE TITLE
[vizbuilder] set default depth level to State on geography dimension types

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#147]
Sometimes, depth zero is not the most explicative level in geography dimensions. 

![image](https://user-images.githubusercontent.com/5233593/44994290-e31b3880-af95-11e8-8c6b-6b9343bd6a61.png)

**Comment by frabarz** [comment]
We could use the defaultLevel attribute for this.
Instead of passing a string, pass an array with default level names and use them if available.
