### ISSUE TITLE
[vizbuilder] use log scales when necessary

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#148]
In Line Plot, when sqrt(SD)/average be much higher than 1, use log scale by default.

**Comment by cnavarreteliz** [comment]
I'm going to calculate the average of dataset and standard deviation for to estimate if we need to use log/linear scale. I thought to implement it only in Line Plots, but StackedArea also has a possibility, what do you mean @davelandry ?
![20180904_095419](https://user-images.githubusercontent.com/5233593/45021288-1529aa80-b029-11e8-9fa2-f5b67b92add6.jpg)

**Comment by davelandry** [comment]
In my opinion, we shouldn't use log scales in stacked charts (stacked bars, stacked areas).

**Comment by cnavarreteliz** [comment]
Ok :)
