### ISSUE TITLE
[vizbuilder] keep a history of queries

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#153]

**Comment by davelandry** [comment]
Did @cesifoti talk about how he wanted this to be displayed? Could this be solved by implementing unique URLs and using the back button?

**Comment by frabarz** [comment]
When we discussed about this, he said he wanted permalinks for the datausa.io/visualize page. It's actually another point on the list, but I didn't include it yet because we need to discuss it; we can't (or at least shouldn't) implement it directly on the vizbuilder.
To have permalinks, we have to use the methods given by `react-router` to the page component to push history state (through the `location` prop) with a change on the query state inside the vizbuilder. This is why I tried to make an update hook attribute in an earlier version, it would make the connection simpler and flexible.

**Comment by davelandry** [comment]
Why should this not be implemented directly in the vizbuilder? I understand we need to use `react-router`, but it's fairly straightforward. It should just be using `replace` on the `browserHistory` (not `push`).

**Comment by frabarz** [comment]
I just pushed the commit with the code for #166. I liked the idea to put a switch for the permalink feature. The other options are a good idea, though it might take me a while.
I put the internal hashed keys thinking specifically on this feature. They were necessary when we worked on the permalink for DataChile's map, but for this case they are stored as private annotations. I'm thinking in the possibility of making them directly in the constructors of `mondrian-rest-client`, though having a unique value coming from the server directly would be even better.
Additionally, I prepared the internal state to store the different queries as they change, so they can be used for a history feature.

**Comment by davelandry** [comment]
Perfect @frabarz! When do you think you'll have a working prototype of the permalinks for me to review?

**Comment by frabarz** [comment]
A few of the features are already working, the vizbuilder currently can parse and present [a shorter version of a permalink](http://vizbuilder.datawheel.us/?ms=20fb9L&dd=2rdnKU), but now I have to adapt it to use variable keys, and after that make it update the current url.

**Comment by frabarz** [comment]
Just pushed [the commit](41b02f024a622be9ac483e23ec769e648633d9b4) with a functional permalink for basic state properties. Now I'll have to decide on a good way to hash a filter/cut combo.

**Comment by frabarz** [comment]
About the permalink functionality, there's a slight problem. There's no way for the Vizbuilder component to directly know when the permalink changes (like when pressing the back/forward buttons), to update the internal state. `react-router` triggers the `@@router/LOCATION_CHANGE` redux event, and that updates the location object passed to the page rendered, but nothing else. To make Vizbuilder aware of this event, we need to pass the location object as an attribute, as this can be used as a reliable indicator for this specific event.
Just to clarify, updating the current location url when the state changes is a working feature at this point, not having this trigger passed to Vizbuilder only disables the behavior in the opposite direction.
Should we add a new attribute to pass this trigger object? or maybe passing it through the permalink attribute?
