### ISSUE TITLE
[vizbuilder] titles in barcharts are too long

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#154]
![image](https://user-images.githubusercontent.com/5233593/44997182-3e542780-afa4-11e8-897c-a2784750077e.png)

**Comment by cnavarreteliz** [comment]
I was experimenting changing orientation to horizontal, hiding ticks in yAxis and putting them over the bar shapes

**Comment by cnavarreteliz** [comment]
@davelandry What do you think about this?

![image](https://user-images.githubusercontent.com/5233593/45154758-91122700-b1d0-11e8-9d95-16894ee60cf1.png)

I want to align the labels to the left!

**Comment by davelandry** [comment]
@cnavarreteliz looks great! yes, you should align the labels to the left:

```js
shapeConfig: {
  labelConfig: {
    textAnchor: "start"
  }
}
```
