### ISSUE TITLE
[vizbuilder] Add multiple source servers (src attribute)

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#156]
We discussed this briefly on Slack, but I thought about it and I'm not sure if I should implement it here or in `mondrian-rest-client`; it could be a neat feature to have there too.

**Comment by davelandry** [comment]
ahh interesting, we could have the mondrian-rest-client accept an Array of URLs when calling `new Client`? I'm ok with whatever solution is easier 😏

**Comment by frabarz** [comment]
I think that instead of modifying the current `Client` class, it would be better to make a new class, something like `MultiClient`. This class could make internally a client for each URL, and have methods to handle the correct client when making a query.
It would help us handle retrocompatibility, and would make it clearer for the user, as we don't have to make overridings for the parameters in each method.

**Comment by davelandry** [comment]
@frabarz makes sense to me! can you create an issue for `MultiClient` in mondrian-rest-client?
