### ISSUE TITLE
[vizbuilder] setting defaultMeasure breaks if the measure name is a duplicate

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#178]
for example, "Household Income" is used in multiple tables

**Comment by davelandry** [comment]
for now, just select the first matching instance

**Comment by davelandry** [comment]
I'm moving this out of the current sprint, as it's not a front-facing issue (it can be worked around for now by only using non-duplicate measures for the default).

**Comment by frabarz** [comment]
As of the current build, I can't reproduce the bug, it's selecting the first match. Can you check it again on your side?

**Comment by davelandry** [comment]
@frabarz confirmed working!
