### ISSUE TITLE
add support for source_for_measure and collection_for_measure annotations

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#180]
@hwchen will be adding these annotations reference [here](https://github.com/Datawheel/datausa-tracker/issues/141). For the vizbuilder, this means 2 changes:
1. hide these measures in the measure selector (just like error_for_measure)
2. show these measures in the tooltips (just like error_for_measure)

**Comment by cnavarreteliz** [comment]
closed vía #181
