### ISSUE TITLE
[vizbuilder] set current value in selector

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#183]
The selector always is selected by default in GEOGRAPHY dimensions.

![image](https://user-images.githubusercontent.com/5233593/46016227-9d402480-c0aa-11e8-90c5-2523381a9901.png)

**Comment by frabarz** [comment]
blueprintjs' Select doesn't allow setting an external value, it's"uncontrolled" by its documentation. It only let listen to changes on its value. The button that opens the list isn't part of the component, to allow the user set a custom design.

This is the intended behavior in all versions, [including the most recent](https://blueprintjs.com/docs/#select/select-component).

**Comment by davelandry** [comment]
@frabarz is this something that could be solved by using the selector that you created?
