### ISSUE TITLE
[vizbuilder] display measure subtitle in closed selector button

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#203]
<img width="285" alt="screen shot 2018-10-01 at 5 18 37 pm" src="https://user-images.githubusercontent.com/1847581/46316396-0ee20c00-c59e-11e8-90c2-e3a0e79f58e0.png">

**Comment by frabarz** [comment]
added in 2a7fa1cee80c5984bf636bf788ad89ca9355aaba
![image](https://user-images.githubusercontent.com/11713191/46461209-7eb9e780-c794-11e8-8650-3a86af08cbe7.png)
