### ISSUE TITLE
[vizbuilder] add data source/name to visualization title

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#204]
each visualization should contain the same text used in the subtitle of the measure selector. you should be able to display this on a new line underneath the title by using a `\n` to separate the two lines

**Comment by cnavarreteliz** [comment]
@davelandry I think that I found a bug in d3plus.

Current Behavior
```title: `${measureName} by ${drilldownName} \n Hello World` ```

![image](https://user-images.githubusercontent.com/5233593/46348932-02ee5c80-c627-11e8-932b-0d40bc0099ee.png)

But if I use `\n` between `""`, the behavior is different.
```title: `${measureName} by ${drilldownName} "\n" Hello World` ```

![image](https://user-images.githubusercontent.com/5233593/46349005-3204ce00-c627-11e8-9486-1e9edcb2ea5e.png)

What do you think??

**Comment by davelandry** [comment]
@cnavarreteliz interesting. can you isolate this in a jsfiddle using only `TextBox` from d3plus-text? it may be an issue with the spaces around the newline, try this: 

```js
title: `${measureName} by ${drilldownName}\nHello World`
```

**Comment by cnavarreteliz** [comment]
You were right! it works! :DD
