### ISSUE TITLE
[vizbuilder] grouping selector missing dimension labels

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#219]
I would expect this selector to look like the measure selector, with each dimension acting like topics do in the measure selector:

<img width="339" alt="screen shot 2018-10-05 at 5 21 28 pm" src="https://user-images.githubusercontent.com/1847581/46560886-511f8c00-c8c3-11e8-866d-0dbf592d8af9.png">

**Comment by davelandry** [comment]
@frabarz I believe this one can be closes, correct?

**Comment by frabarz** [comment]
I'm not sure if it got correctly solved at the time, but with the change in the Select component it should be working differently. I think we can close it.
