### ISSUE TITLE
Random console outputs creating shelljs files

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/canon#22]
On a deployed canon instance there appear to be random shelljs_* files being created.

![screen shot 2017-08-02 at 11 46 00 am](https://user-images.githubusercontent.com/252276/28882170-734783b6-7778-11e7-97e6-8d360e3f0466.png)

**Comment by davelandry** [comment]
@alexandersimoes can you confirm if this is still happening? and if so, can you tell us which server you are seeing this happen and post that server's `package-lock.json` file here?
