### ISSUE TITLE
[vizbuilder] filters not working

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#222]
When adding a new filter, it does not appear to be actually filtering the data, and when I press "edit params", I'm presented with an empty filter box. Here's the configuration I'm testing with:

<img width="301" alt="screen shot 2018-10-11 at 12 35 05 pm" src="https://user-images.githubusercontent.com/1847581/46819639-44cb8100-cd52-11e8-95ea-a2a68fdb8f96.png">

**Comment by frabarz** [comment]
I tried other combinations and some of them work fine, so I'll debug the logic for this one first.

**Comment by frabarz** [comment]
the issue seems fixed on fossil-lake, so I'll close it for now
