### ISSUE TITLE
[vizbuilder] increase TooMuchData cap and make env var

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#223]
Currently, I'm unable to create a county map in the vizbuilder, because ~3221 US Counties times the number of years available is over the `9999` limit for too much data. Ideally, we shouldn't need this message and our visualizations should be able to handle everything we try to do, but for now let's increase this limit to something like `20000` and also allow the user to set this using an env var: `CANON_VIZBUILDER_DATACAP`

If there was any way to take the number and divide it by the number of years, that would also be a great solution to help with this.

**Comment by jspeis** [comment]
in this specific case it might also make sense to only load data for one year at a time where possible for responsiveness since its likely extremely difficult (impossible?) to meaningfully analyze 3221 separate entities in a time-series visualization anyway

**Comment by davelandry** [comment]
except for the case of a Geomap, you'd want to be able to change years and see the counties change

**Comment by jspeis** [comment]
sure, but if we already have each cube's year span cached, could the other year's data only load if the usually actually selects a different year?

**Comment by davelandry** [comment]
Theoretically yes, but that's not necessary the problem we're facing here and might be an overcomplication... it's more an issue with the visualization not being able to support/draw a huge amount of shapes, rather than data size itself. We've started to catch for this in certain visualizations (like not rendering bar charts if too many bars), so this should be something caught at the visualization level, not at the query level.
