### ISSUE TITLE
[vizbuilder] add more default formatters

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#226]
This is the current list of `units_of_measurement` available in the canon-api server:

```
"Dollars"
"Number"
"Households"
"Percentages"
"Sample Records"
"USD"
"MOE"
"Years"
"Hours"
"RCA"
"Degrees awarded"
"Universities"
"Percentage"
"Growth"
"NONE"
"Minutes"
"Noninstructional employees"
"People"
"Jobs"
"Rate"
"Thousands of Tons"
"Count"
"Bachelors degrees completed"
"Occupied Households"
"Percentile"
"Applicants"
"Admitted Students"
"Admitted Students, Men"
"Admitted Students, Women"
"Admitted Students Who Enrolled, Men"
"Admitted Students Who Enrolled, Women"
"Admitted Full-Time Students Who Enrolled"
"Admitted Full-Time Students Who Enrolled, Men"
"Admitted Full-Time Students Who Enrolled, Women"
"Admitted Part-Time Students Who Enrolled"
"Admitted Part-Time Students Who Enrolled, Men"
"Admitted Part-Time Students Who Enrolled, Women"
"Number of Applicants Submitting SAT Scores"
"ED visits per 1,000 Medicare beneficiaries"
"deaths per 100,000 population"
"Percent"
"Micrograms Per Cubic Meter"
"Deaths"
"Ratio"
"Yes or No"
"Index"
"Days"
"Hospital Stays"
"Cases"
"Associations"
"Births"
"Crimes"
"Number of Borrowers"
"Enrolled students"
"Employment"
"Openings"
"deaths per 1,000"
"Housing Units"
"Millions of Dollars"
"Instructional employees"
"Months"
"Gini Index"
"Number of loans"
"Employees"
```

In the first commits for #225, there are default formatters for `Dollars` and `USD`. Which ones should we add by default?
Percentage/Percent should be, but we might want to standarize if the raw value range should be [0,1] or [0,100].

**Comment by davelandry** [comment]
Moving forward, let's use "Percent" for as-is percentages, and "Rate" for numbers that need to be multiplied by 100. I've also created some issues for @jspeis and @hwchen to clean up certain annotations to match this standard.

@frabarz here is the first set of formatters we should account for (written in pseudo-code). Everything other than these (and the current Dollars/USD) should use `formatAbbreviate` by default:
* `Percentage: d => formatAbbreviate(d) + "%"`
* `Growth: d => formatAbbreviate(d * 100) + "%"`
* `Rate: d => formatAbbreviate(d * 100) + "%"`
* `Ratio: d => formatAbbreviate(d) + " to 1"`
* `"Thousands of Dollars": d => "$" + formatAbbreviate(d * 1000)`
* `"Millions of Dollars": d => "$" + formatAbbreviate(d * 1000000)`
* `"Billions of Dollars": d => "$" + formatAbbreviate(d * 1000000000)`
* `MOE`/`LCI`/`UCI` - error measures should infer their formatting from the measure they correspond to
