### ISSUE TITLE
[CMS] Refactor Move Buttons into Cards themselves

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#239]
Currently the MoveButton component lives next to each card (generatorCard, textCard, visualizationCard, selectorCard) in a div.

Similar to footerbuttons, the Movebuttons should be INSIDE the cards themselves - such that they know how to move themselves around with their siblings, and we need not repeat movebuttons at the top level profile/section/topic editors

**Comment by jhmullen** [comment]
Note from @davelandry - consider moving this to a cog setting on the card

**Comment by davelandry** [comment]
was this completed by @perpetualgrimace?

**Comment by perpetualgrimace** [comment]
Sort of. It's still a separate component, passed through to the cards and rendered as `props.children`.
