### ISSUE TITLE
[CMS] Move Nested Creates to API instead of Front-end JS

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#241]
Currently, when the CMS does something like create a profile, we scaffold its child elements (section and topic) at the *javascript* level, waiting for the profile to finish, creating the section, etc. 

This should be moved to the API level (such that creating a profile intrinsically creates its children). Ideally, it should be moved even LOWER to the postgres level, such that cascading Creates are part of the Sequelize model itself.

**Comment by jhmullen** [comment]
@davelandry On what timescale do you see us tackling #383? This issue is mostly a good-dooby programming change - one that will go away when we tackle the flattening rewrite.

**Comment by davelandry** [comment]
Good point. I don't have a timetable for #383, but we shouldn't bother doing this since we see that on the horizon.
