### ISSUE TITLE
[vizbuilder] custom selector cuts off long measure names

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#259]
Desired behavior would be to wrap the text, but if that's too hard, we should be using ellipsis:

<img width="296" alt="screen shot 2018-10-29 at 12 40 32 pm" src="https://user-images.githubusercontent.com/1847581/47665627-e71f9d00-db77-11e8-95c4-1d6b00333de3.png">

**Comment by frabarz** [comment]
the correction for this issue was included in #254, should be merged now

**Comment by davelandry** [comment]
@frabarz if the implementation for wrapping is easy, let's do it!
