### ISSUE TITLE
[vizbuilder] remove "undefined" source and collection from tooltips

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#293]
https://joshua-tree.datausa.io/visualize?groups=0-z7J78&measure=Z1hS30j

<img width="345" alt="screen shot 2018-11-15 at 4 00 24 pm" src="https://user-images.githubusercontent.com/1847581/48581372-a0f46880-e8ef-11e8-9268-5aefc9d13132.png">

**Comment by frabarz** [comment]
#257 already does this, but the dataset has an issue where only District of Columbia in 2018 shows an actual value and everything else is undefined. Walther is already investigating it.

I'm not sure how mondrian handles it in intended cases, though. Should I make it say `0` when the value from the server is `undefined`? reminder I have to decide how to handle it seeing all values before rendering.
