### ISSUE TITLE
[vizbuilder] unable to define a custom fitFilter

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#309]
Trying to do this:

```jsx
<Vizbuilder config={{fitFilter: myFunction}} />
```

Probably related to this line: https://github.com/Datawheel/canon/blob/a773aa24dcd5ed6226fc0a53fc1f539a8d7ce258/packages/vizbuilder/src/helpers/chartconfig.js#L205

This shouldn't get set if the user has defined one.

**Comment by davelandry** [comment]
@frabarz I'm still having trouble setting this. Here's a live example (in d3plus) of the behavior I'm trying to achieve: http://jsfiddle.net/dr8ycq4b/

**Comment by frabarz** [comment]
Are you sure? I tried in my local and can't replicate:

![image](https://user-images.githubusercontent.com/11713191/50387172-e6693a00-06d4-11e9-9f8b-d4531a04b19a.png)

![image](https://user-images.githubusercontent.com/11713191/50387167-c76aa800-06d4-11e9-82d6-931c2d857344.png)

**Comment by davelandry** [comment]
@frabarz hmm, ok I'll dig deeper.
