### ISSUE TITLE
[cms] rename "UI" and "JS" modes

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#348]
They should be "Simple" and "Advanced".

**Comment by perpetualgrimace** [comment]
Disagree. Isn't simple/advanced mode a little condescending? To me it sounds like genius expert mode and baby n00b mode. In reality, the UI mode can be useful to developers and non-developers. 

How about visual mode and javascript mode?

**Comment by perpetualgrimace** [comment]
That's the case with almost any UI, is it not?

**Comment by davelandry** [comment]
🙇
