### ISSUE TITLE
[cms] style selector modal

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#367]
<img width="949" alt="screen shot 2018-12-18 at 11 41 58 am" src="https://user-images.githubusercontent.com/1847581/50168686-f7bbdc00-02b9-11e9-9bee-73ee700d8373.png">

**Comment by perpetualgrimace** [comment]
Feature or bug? 😂

**Comment by perpetualgrimace** [comment]
<img width="918" alt="screen shot 2019-01-10 at 6 23 08 pm" src="https://user-images.githubusercontent.com/6193798/51003448-d50d9380-1504-11e9-9ab3-01934cfaddfd.png">

Somewhat better.
