### ISSUE TITLE
[CMS] Redesign / Flatten Underlying CMS structure

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#383]
Currently, the CMS has a hard-coded hierarchy of profiles, sections, and topics. However, over a few months of real-life use with the CMS, we have found that a strictly hierarchical structure adds a lot of complicated overhead to both the codebase and the user interface. Codewise, there is a lot of complexity to managing parents and differentiating between profile visualizations and topic visualizations, etc. UX-wise, the strictness of the hierarchy can be limiting in the kinds of pages one can make (one can't have a topic without a section, and so on).  

Consider a flattened version: There are no longer profiles, sections, and topics, but in essence, "Everything is a topic," or more generically, everything is the same entity.

A great many of the entities in the CMS share functionality - profiles, sections, and topics for example all have database structures that allow them to have several ordered `description` paragraphs.  In some cases, only two of the three share functionality - profiles and topics can have visualizations, but sections cannot.  

We should collapse these entities into one single entity - one capable of having visualizations, selectors, or just a title alone.  A "page" would then be a simple one-dimensional ordered list of entities of varying types.  In truth, this is what pages already __are__.  DataCountry's "infinite scrolling" style gains no functionality from the fact that topics "belong to" sections.  These data pages are essentially _"One Dimensional Ordered Lists of Entities that Make Use of One or More of a Standardized Set of Visual Elements"_, and the CMS should reflect that.

This is a hefty undertaking, but the basic tasks would be:

- [x] Collapse ProfileEditor, SectionEditor, and TopicEditor into a single EntityEditor that contains all possible elements
- [x] Collapse database structure to match the new singular Entity and all its children.
- [x] Establish a list of "Common Types" of entities that can be displayed in a dropdown.  This would allow a user to identify/tag an entity as a certain __type__ for use on the front end rendering. So for example, an entity tagged as a "section" would be displayed in a certain way with a large title font. But in truth, this is still the same entity that could have vizes or selectors - it's just that this one doesn't happen to have them
- [x] Revamp ProfileBuilder to no longer contain all the "nesting" that was necessary for the hierarchy. 
- [x] Replace `Tree` Sidebar with drag&drop reorder, or at least a single 1d List.

**Comment by davelandry** [comment]
@jhmullen hey you did this?

**Comment by jhmullen** [comment]
Yes, this was all in the `refactor-flatten` branch and was merged.
