### ISSUE TITLE
[core] allow DB models to include seed content

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#389]
Putting this under the CMS project, as it directly relates to a feature used there (formatters).

**Comment by jhmullen** [comment]
You should be good to go on this @davelandry once PR #390 moves all the formatters into `/src/utils/formatters`.

**Comment by davelandry** [comment]
What makes you think you're not going to end up doing this? 🤣

**Comment by jhmullen** [comment]
`ffffffff-`

**Comment by davelandry** [comment]
Hey... we did this! Part of canon-core v0.17.6
