### ISSUE TITLE
[cms] profile 404 kickbacks

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#425]
- [x] the profile API route should return an error when the ID or slug is invalid (implemented in Data USA [here](https://github.com/DataUSA/datausa-site/blob/91d9a7a75db2801af658c2f0159bcdda77edef62/api/mortarRoute.js#L235)) @jhmullen 
- [ ] create a 404 state in the front-end Profile component @davelandry

**Comment by jhmullen** [comment]
@davelandry PR #984 contains the 404 passthrough. Branch is called `issue-425-404s`.
