### ISSUE TITLE
[core] if default language is not set, take first language from CANON_LANGUAGES

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#428]
Using `0.17.4` version, if you doesn't set explicity `export CANON_LANGUAGE_DEFAULT=lang`, the translations in multilanguages projects don't work

**Comment by jhmullen** [comment]
For the sake of being explicit over implicit, I consider the `CANON_LANGUAGE_DEFAULT` variable to be a requirement for canon.
