### ISSUE TITLE
[cms] react-quill doesn't allow inline HTML

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#430]
Take a look at the first story in the CDC as an example. If a user of the CMS tries to insert their own HTML code, like an `<img src="" />` to be displayed, react-quill changes the left and right angle brackets into HTML escaped characters (and just displays the code as a string).

I can't see a world where we would want this behavior... the only time we would want to display the code itself we should just require users to put it in a code block using the UI buttons.

**Comment by jhmullen** [comment]
We are no longer using Quill, so I am closing this issue.
