### ISSUE TITLE
[vizbuilder] show secondary cut in label

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#435]
For example, in [this](https://saguaro.datausa.io/visualize?groups=0-BNDBG&groups=1-1WnF7j-DOC~MAS&measure=1g4zN3) configuration:

<img width="1261" alt="screen shot 2019-02-13 at 2 49 24 pm" src="https://user-images.githubusercontent.com/1847581/52739725-80e04e00-2f9f-11e9-98c7-62d9bdcdfc6e.png">

It gets confusing which squares are which (without hovering over to see tooltips). For example, the first bar in the bar chart should read `Women (Doctoral Universities)`

**Comment by frabarz** [comment]
what should we do in case any of the labels is too long? should we just let `d3plus-text` take care of that?

**Comment by davelandry** [comment]
yeah, `d3plus-text` should automatically take care of any text wrapping and truncation. Let's see how it looks. In any case, I would argue that even seeing something like `Women (Doctoral...` is better than just `Women`
