### ISSUE TITLE
[logiclayer] filter by Year not working

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#443]
URL: [http://estonia.datawheel.us/api/data?Flow=1&drilldowns=HS4,Year&measures=Total&parents=true&Year=2010&captions=en](http://estonia.datawheel.us/api/data?Flow=1&drilldowns=HS4,Year&measures=Total&parents=true&Year=2010&captions=en)

##### Logic Layer log:
```
Logic Layer Query: exports_and_imports
Measure: Total
Cut: [Flow].[Flow].[Flow].&[1]
Drilldown: Product, Product, HS4
Drilldown: Flow, Flow, Flow
Parents: true
```

**Comment by davelandry** [comment]
@cnavarreteliz the logic for identifying the Year dimension wasn't accounting for the `dimensionType` property passed from mondrian-rest-client. I've added support for this and your query (also including `latest`, `previous`, etc) should now be working with the v0.3.11 release.
