### ISSUE TITLE
[vizbuilder] add support for "SAT Score" units_of_measurement

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#444]
For now, let's set up the following 2 rules:
- [x] no Stacked Area Charts (should not be aggregated)
- [ ] when displaying on an x or y axis, set `domain: [0, 800]`

Data USA link: https://theodore.datausa.io/visualize?groups=0-1W4bia&measure=Z1uA3zw

**Comment by frabarz** [comment]
using `baseline: 0` I get this chart
![image](https://user-images.githubusercontent.com/11713191/53360833-5da98d00-3915-11e9-9b73-239b8d343877.png)
is it ok?

**Comment by davelandry** [comment]
@frabarz yup! Looking at this, let's do it a different way: `yConfig: {domain: [0, 800]}`. SAT scores will always be within that range 😄

**Comment by frabarz** [comment]
but that would mean hardcoding a config, shouldn't that go in a `measureConfig`?

**Comment by davelandry** [comment]
@frabarz that's a fair point, I'll take care of that in the front-end.

**Comment by davelandry** [comment]
@frabarz I'm actually unable to use the front-end for this, as setting `yConfig: {domain: [0, 800]}` for the SAT measures will break any x/y chart that does not have the measure on the y-axis (specifically the horizontal Bar Charts).

Unless I'm doing something wrong, I think we should hard code this as part of the LinePlot configs, specific for this `units_of_measurement` type.

**Comment by davelandry** [comment]
Take a look at this endpoint: /visualize?groups=0-1W4bia&measure=Z1uA3zw

We need to set the `xConfig` on the first chart, and the `yConfig` on the second chart.
