### ISSUE TITLE
[vizbuilder] force y-axis domain to start at 1 on non-divisible units of measurement

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#448]
Units like "People" or "Households" would be eligible.
It would be more important to apply if the scale is log instead of lineal.

**Comment by davelandry** [comment]
there are 2 different ways you could approach it. The first (and easiest) is to set `baseline: 1` in the config object. If that doesn't work for all LinePlots, than you would have to calculate the max value and pass the full domain to: `yConfig: {domain: [1, maxValue]}`

**Comment by davelandry** [comment]
I'm fine closing this for now, until we have specific new measures to add in.
