### ISSUE TITLE
[vizbuilder] add a way to apply multiple changes on groups at once

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#449]
maybe make a new button appear if there's many unapplied changes on the groups' options
it's kinda discouraged to do this because vizbuilder reverts to the last stable state if the query fails or has TooMuchData™, which would mean the user wouldn't know which part of their query was the cause

**Comment by davelandry** [comment]
Closing all `[vizbuilder]` issues, as the canon-vizbuilder package is no longer in development in favor of the more generic https://github.com/datawheel/vizbuilder package
