### ISSUE TITLE
[vizbuilder] make "Other" bucket category for treemaps with high granularity

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#450]
![image](https://user-images.githubusercontent.com/11713191/53038473-9cde6680-345b-11e9-89c2-d3d5541d2840.png)
Treemaps like these aren't very clear. We should make a bucket and aggregate the minor cases, but before that establish a good criteria to make the aggregation.

**Comment by davelandry** [comment]
@frabarz we had a feature like this in the old d3plus that analyzed the data and grouped anything < 2% of the overall total into a separate "Values < 2%" group.

**Comment by davelandry** [comment]
moved to d3plus-viz: https://github.com/d3plus/d3plus-viz/issues/111
