### ISSUE TITLE
[vizbuilder] only show members with data

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#453]
I'm not sure on the feasibility of this, but I'm wondering if there's any way on the front-end that we can only allow the users to filter by members that have data? For example, take a look at Obligation Amount for the "Commision of Fine Arts":

<img width="1265" alt="screen shot 2019-02-20 at 8 43 56 am" src="https://user-images.githubusercontent.com/1847581/53095880-d8287600-34eb-11e9-81d6-78934f635333.png">

https://ulysses.datausa.io/visualize?groups=0-Z1MxM8L&groups=1-ZAQr0a-9537&measure=1e64mv

This makes some sense in this context, but if you add another filter that has data (like "Federal Trade Commision"), it makes it seem like the Vizbuilder is incorrectly only showing 1 of the cuts.

If there's no way to "check for data" on the front-end, maybe we can add annotations to members on the back-end? Looking for @jspeis's thoughts here as well.

**Comment by jspeis** [comment]
In this case I don't think the solution is to use annotations, as what lives in the schemas should not vary over time with changes in the data. Two options in this instance to check could be either:

1. cache an endpoint at server startup to get a list of agencies with Obligation Amounts > 0. 

2. how is the member list populated at this point? perhaps that member list could be swapped with an API call instead such that only if a user actually selects that they want to filter on agencies, at that point it queries the API to see a list of agencies that actually have data.

Though overall I'm not sure

**Comment by davelandry** [comment]
@frabarz any thoughts? I like using the members all to populate the list, as fetching the entire dataset might take much longer (but maybe not?)

**Comment by frabarz** [comment]
Currently the vizbuilder handles all general use data from the `/cubes` endpoint.
After selecting a Level in the group selector, their `/.../level/<levelName>/members` are loaded immediately to offer the user the list of available cuts. We should do the filtering at this point.

What do you think about this? I could make a second query in the background, at the same time as with members, that only drills the level. When both requests load, I iterate over the information and filter the members that don't have items. This won't be a problem with Levels with few members, but could affect the experience if there are many.

**Comment by davelandry** [comment]
Hmm, I'm not that big of a fan of making both the `members` request AND the `data` request. Could we JUST do the `data` request and use that for the member list?

**Comment by frabarz** [comment]
Apparently, if I use `json` format instead of `jsonrecords`, I get a list of members in the same shape as the `/members` endpoint, but only with members included in the data. I can use this.
Note this data request goes before the data request that's used for the charts.
