### ISSUE TITLE
[vizbuilder] add ability to cut and drill on different levels

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#465]
An example would be [this query](https://voyageurs-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJDb3VudHkiLCJDb3VudHkiXV0sImN1dHMiOltbWzMxXSxbIkxhbmd1YWdlIFNwb2tlbiBhdCBIb21lIiwiTGFuZ3VhZ2UgU3Bva2VuIGF0IEhvbWUiLCJMYW5ndWFnZSBTcG9rZW4gYXQgSG9tZSJdXSxbWyIwNDAwMFVTMDYiXSxbIkdlb2dyYXBoeSIsIkNvdW50eSIsIlN0YXRlIl1dXSwiY3ViZSI6ImFjc195Z2xfbGFuZ3VhZ2Vfc3Bva2VuX2F0X2hvbWVfYnlfZW5nbGlzaF9hYmlsaXR5XzUiLCJtZWFzdXJlcyI6WyJMYW5ndWFnZXMgU3Bva2VuIl19), where I get information drilled on the County level, but also cut for the `California` State level.

**Comment by davelandry** [comment]
@frabarz what do you think about this implementation:
1. user selects "County" grouping
2. user adds new grouping
3. user is able to see the same Geography grouping again in the new grouping menu, but ONLY levels above their previously selected level
4. when choosing "State" grouping, the vizbuilder knows to only apply this additional grouping if they have defined cuts

**Comment by davelandry** [comment]
Closing all `[vizbuilder]` issues, as the canon-vizbuilder package is no longer in development in favor of the more generic https://github.com/datawheel/vizbuilder package
