### ISSUE TITLE
[vizbuilder] add "Clear" button on sidebar groupings/filters

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#467]

**Comment by davelandry** [comment]
@frabarz noticed a couple of small issues with the current behavior:
- [ ] the button should apply to both the groupings and the filters
- [ ] the button should be positioned underneath the data source info, right above where `children` get rendered
- [ ] changing the default grouping from States to PUMA should activate the button (it does not)
- [ ] change icon to "pt-icon-undo"
- [ ] change text to "Reset to Defaults"
