### ISSUE TITLE
[cms] Handle cube failures more gracefully

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#469]
In cmsRoute, on profile creation, we attempt to populate the search table based on a cube query.  Right now, if the cube is corrupted or times out in some way, the profile creation fails.

Catch a cube timeout and provide a warning to the user, but allow the profile creation to complete.

**Comment by davelandry** [comment]
@jhmullen with the decoupling work you've been doing, has this been addressed?

**Comment by jhmullen** [comment]
This has long been fixed, profiles can be created before they are populated with cube data.
