### ISSUE TITLE
[cms] multilingual search

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#471]
Right now we default to english when we populate the search table.  

Long term:

- [x] split the search table into two tables - actual items and language content
- [x] refactor the search endpoint to have a `?lang=` flag which filters content and returns ids

I have moved some QoL tasks to #638 so that a multi-lang MVP can get out the door. For now, when a user adds a new language, he or she will have to rebuild the search index manually in the CMS interface.

**Comment by davelandry** [comment]
For the search endpoint itself, base it off of the current `staging` Data USA endpoint. It uses `lunr` (which will be a new dependency) for creating a search index in cache:
https://github.com/DataUSA/datausa-site/blob/staging/cache/searchIndex.js

And then the express route is here:
https://github.com/DataUSA/datausa-site/blob/staging/api/searchRoute.js
