### ISSUE TITLE
[vizbuilder] low-quality titles on charts from new query kind

### ISSUE THREAD

**Issue by frabarz** [Datawheel/canon#475]
This chart was being output by a combination2-query 
![image](https://user-images.githubusercontent.com/11713191/53667107-c9119880-3c4e-11e9-9f17-83f7186aaabb.png)

This new chart is output from the new blind-cut-query
![image](https://user-images.githubusercontent.com/11713191/53667148-e5153a00-3c4e-11e9-9c9d-15d1b080ad32.png)

The title is not using useful information. The second chart replaces the first after applying the duplicated chart filter.

**Comment by davelandry** [comment]
@frabarz I'd like to propose some new title logic. In addition to this catch 👆 that you found, we're also having trouble with the charts further down in the page that don't contain all of the specific cuts. Take this build for example: https://windcave.datausa.io/visualize?groups=0-1cCiqp&groups=1-ZdEVTH-11&measure=ZjsmSE

Users are having confusion between the first map and the second map:
- First title: "Languages Spoken for Russian (2015)"
- Second title: "Languages Spoken by State (2015)"

Ideally, I think it could help if the titles were like this:
- First title: "Languages Spoken by State for Russian (2015)"
- Second title: "Languages Spoken by State for All Language Spoken at Home (2015)"

So with that in mind, the construction of a title would look something like this:

```jsx
`${measure} by ${all drilldowns joined with "and"} for ${all filters joined with "and"}`
```

And if the current chart does not use one of the drilldowns or filters, simply replace the specific cut with the name of the "All" level.
