### ISSUE TITLE
[vizbuilder] optimizations

### ISSUE THREAD

**Issue by jspeis** [Datawheel/canon#496]
* for PUMS cubes avoid calling `parents=true` in the data calls if the parents are not used (this slows and bloats the returned data)
* Limit queries to a maximum total of 5 drill downs and cuts (i.e drilldowns+cuts <= 5)
* support `hide_in_map` at the cube level (@hwchen added this annotation to the Hispanic population cube but seems like it is not currently noticed at the cube level?)

**Comment by davelandry** [comment]
split into separate issues:
* #497 
* #498
* #499
