### ISSUE TITLE
[vizbuilder] deterministically call parents=true

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#497]
@jspeis has suggested that always calling `parents=true` bloats the data, causing in slowness.

@frabarz are these parents used internally for anything? I know that we sometimes use them in the front-end for coloring, but it would be great to give me a way to determine if it should be called depending on the query:

```jsx
parents={query => {
  // logic to inspect the current query and determine if parents should be true or false
  return true;
}}
```

**Comment by frabarz** [comment]
`parents=true` is currently used in the dataset to enable groups in the treemaps. The current criteria to load them is `parents: drilldownList.some(dd => dd.depth > 1)`, which technically leads to always loading them if they exist.

**Comment by davelandry** [comment]
I'm going to close this issue for now, as these `parents` are generally helpful for both the vizbuilder itself and the site implementing it for styling. The current `depth > 1` is great to at least not load them if you are looking at something without parents.
