### ISSUE TITLE
[vizbuilder] limit groupings to 3 total

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#498]
1. create new `groupLimit` prop (default value of `3`)
2. once a user has added the `groupLimit` of groupings, hide the "add grouping" button

```jsx
<Vizbuilder groupLimit=10 ... />
```

**Comment by frabarz** [comment]
The UI now blocks adding more than `props.groupLimit` groups to the sidebar, but you still can add more using a crafted permalink. I'll fix that when I'm working on another issue that involves permalinks too, because I have to make big changes on the way permalinks are being managed.
