### ISSUE TITLE
[vizbuilder] only show deepest level of visualizations

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#503]
Currently, every combination of groupings and cuts is displayed as visualizations, but we've found through testing that this adds too much to load time and confusion between charts. For now, let's remove this logic (instead of doing #488)

**Comment by frabarz** [comment]
Just to clarify, vizbuilder currently builds these queries:

1. A query for each grouping alone, with cuts if the grouping has members applied.
2. A query for each combination taking 2 from all groupings available, with cuts if their groupings have members applied.
3. A query with all the groupings and cuts applied.

We are removing (1) and (2)?

**Comment by davelandry** [comment]
@frabarz yup, the idea would be to remove 1 and 2, and only show 3
