### ISSUE TITLE
[vizbuilder] double load when changing a cut?

### ISSUE THREAD

**Issue by jspeis** [Datawheel/canon#504]
it looks like the vizbuilder will refresh twice when changing a cut? try these steps to reproduce in chrome

1. visit `/visualize?groups=0-z9TnC&groups=1-1SyFhe-200&groups=2-1mjmRl-711&measure=1qWfo`

2. edit afganistan to alabama (or some other place) and click apply

3. it appears the data is loaded and shows briefly but then appears to reload again?

**Comment by davelandry** [comment]
moved to https://github.com/DataUSA/datausa-site/issues/837
