### ISSUE TITLE
[vizbuilder] only show year on x-axis charts with more than 1 year available

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#512]
https://preview.datausa.io/visualize?groups=0-21zaCk&groups=1-2rAHKG-2&groups=2-Z5TtG5-2&groups=3-ZJJp1G-51913&measure=ZkH9RT

**Comment by frabarz** [comment]
This was caused by a bug on the topten line chart part of the code. I'll push a fix asap.
