### ISSUE TITLE
persist grouping level across cubes if name matches

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#525]
If a user is looking at a County map, and they switch to a measure in a different cube, it would be great if the viz builder had some logic to try and maintain the "County" level, even though the internal IDs are different across cubes. 

For example:
1. start at this URL: https://datausa.io/map?enlarged=c-geomap-Z1X72Pg&groups=0-Z1X72Pg&measure=1EMql9
2. change the measure to "Foreign-Born Citizens"
3. get brought to a State map: https://datausa.io/map?enlarged=c-geomap-1dX7e9&groups=0-1dX7e9&measure=ZHkGoL

@frabarz do you think this is doable?

**Comment by frabarz** [comment]
This feature is actually part of the current code, but it's only being applied to measure changes between the same table. In this case, the measures don't belong to the same table, so the algorithm is skipped.

**Comment by frabarz** [comment]
It would, the code is isolated in a function, so it should be just modifying the condition for how it loads.
Although there's something I want to check: the algorithm only produces the intended behavior if all the dimension, hierarchy, and level have the same name, which could sometimes conflict with levels that belong to the same dimension but not to the same hierarchy (like Geography.County.County and Geography.State.County); should I make it more permissible, to match other hierarchies if there's no matches on the same one?

PS: 🤔
![image](https://user-images.githubusercontent.com/11713191/57394534-cde55200-7193-11e9-8dd8-ad36c038b190.png)

**Comment by davelandry** [comment]
@frabarz yes, more permissible (if there are no matches)

regarding that timestamp, I'm testing my new time machine ¯\_(ツ)_/¯
