### ISSUE TITLE
[cms] implement global toolbox

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#529]
A new drawer element on the right side of the CMS that persists even when no profile is selected. It would have the following features:

- dropdown to select viewable items:
  - "All" (maybe we don't need this one?)
  - Formatters
  - Variables (if a profile is active)
- search box to filter results by:
  - title match
  - description match
  - variable match (generators only)
- grouping toggle for variables (generators vs variables)
- scrollable list of results, clicking would open the modal editor
- an "add new" button to create new items (maybe only if "All" is not selected?)

![IMG_2767](https://user-images.githubusercontent.com/1847581/57335868-fa489200-70f1-11e9-8c74-acda578150fd.jpg)

This is how I see the division of labor happening:
- [x] create the component to hold these items (@jhmullen)
- [x] move formatters from tab into the drawer (@jhmullen)
- [x] move generator cards from Profile landing into the drawer (@jhmullen)
- [x] get filter/search capabilities working (@jhmullen)
- [x] style the hell out of it  (@perpetualgrimace)

**Comment by jhmullen** [comment]
Reopening this, to be closed when the PR is merged.
