### ISSUE TITLE
[vizbuilder] unable to search country members

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#531]
<img width="342" alt="Screen Shot 2019-05-09 at 4 10 59 PM" src="https://user-images.githubusercontent.com/1847581/57640506-acfc7280-7580-11e9-825a-0915152a41e5.png">

**Comment by frabarz** [comment]
In this case the problem is related to the cube; there's an issue with the hierarchies. I'll update after the cube has been reviewed.

**Comment by jhmullen** [comment]
@frabarz can this be closed?

**Comment by davelandry** [comment]
Closing all `[vizbuilder]` issues, as the canon-vizbuilder package is no longer in development in favor of the more generic https://github.com/datawheel/vizbuilder package
