### ISSUE TITLE
add "share" option to visualization dialog window

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#534]
@perpetualgrimace how feasible would it be to port over the share behavior you set up in Open Compass to exist right in line for topics in the CMS?

https://github.com/Datawheel/canon/blob/master/packages/cms/src/components/Topic.jsx#L69

**Comment by perpetualgrimace** [comment]
I'm sure it's doable. I would need to sit down with you and understand how it fits in.

**Comment by davelandry** [comment]
@perpetualgrimace this would be the perfect opportunity to get you into the guts of how the CMS actually _renders_ a profile. I'm excited. Not next week, but maybe the week after that?

**Comment by perpetualgrimace** [comment]
closed via #536
