### ISSUE TITLE
[cms] design new dimension components

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#538]
In the `feature-bivariate` branch, please take a look at the following components:
- [x] DimensionCreator
- [x] DimensionBuilder
- [x] DimensionCard

**Comment by perpetualgrimace** [comment]
Current progress:

Dimension creator:
<img width="932" alt="dimension-creator" src="https://user-images.githubusercontent.com/6193798/58642201-d4667580-82ca-11e9-82ec-dd42d1fb5aab.png">

Dimension cards:
<img width="1230" alt="dimension-cards" src="https://user-images.githubusercontent.com/6193798/58642273-01b32380-82cb-11e9-9363-e38f8e7b7111.png">
