### ISSUE TITLE
Add a PostCSS URL processor

### ISSUE THREAD

**Issue by jazzido** [Datawheel/canon#56]
We serve different content on different subdomains (locale selection), but we would still like to have a common virtualhost for static content (like a CDN). We created a very simple [`asset_url` helper](https://github.com/Datawheel/datachile/blob/asset-host/app/helpers/url.js#L12), but we still need to rewrite links in CSS.

There seems to be a number of options for doing that in PostCSS ([`postcss-url`](https://github.com/postcss/postcss-url) is one of them). We don't have access to webpack configuration, so we hereby summon the Canon Master.

Sketch: if `CANON_CDN_URL_BASE` exists as an environment variable, that plugin is added to `postCSSConfig` with the proper configuration.

**Comment by jazzido** [comment]
For now, we can make do by processing our CSS files with `sed` (before the Canon build). But having this we'd be awesome.

**Comment by jazzido** [comment]
Additionally, if `CANON_CDN_URL_BASE` (or something to that extent) is present, the app bundle should also be served from there.

**Comment by jazzido** [comment]
How can I help you implement this? (Besides sending a PR? :)) We'd love to move our static assets to a separate hostname.

**Comment by davelandry** [comment]
@jazzido is the main functionality here just basically: "prepend a string to all CSS urls"?

If so, yeah, we should totally do that. I'd suggest something like `CANON_CDN`, with the assumption that if present, all CSS links should be relative to that CDN. 

Past the concept, I've just never used postcss-url to do that... has anyone used that plugin before? It would just need to be added here: https://github.com/Datawheel/datawheel-canon/blob/master/webpack/config/postcss.js

**Comment by jazzido** [comment]
I've never used it either. I mentioned it because it popped up when I googled around for a solution.
We will also need the CDN base to be available as a global const, for generating links to static assets.

**Comment by davelandry** [comment]
we recently added the `[CANON_BASE_URL](https://github.com/Datawheel/datawheel-canon#additional-environment-variables)` environment variable... which sets the `<base>` tag in the head of the page. This string prepends any static link on the page that does NOT start with a forward slash. Maybe this solves this problem?
