### ISSUE TITLE
[cms] better visualization JS error handling

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#564]
- [x] show "stack trace" in CMS (@jhmullen)
- [x] show a default "Error Building Visualization" message in front-end (@davelandry)
- [x] allow users to override via d3plus.js and custom config (@davelandry)

**Comment by davelandry** [comment]
@jhmullen is this... done?

**Comment by jhmullen** [comment]
Yes, this was done in https://github.com/Datawheel/canon/commit/c9ade2b174f920c2a79e13cbc5e269780cf0384a

Thanks for the reminder ping.
