### ISSUE TITLE
[cms] include auth options to new env var

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#574]
Sometimes, the server has `user / password`. In those cases, we cannot to establish connection with the API, receiving an 401 error from the server. 

I would like to include environment vars like `CANON_CMS_AUTH_USER` and `CANON_CMS_AUTH_PASS`

Ref: [https://stackoverflow.com/questions/44072750/how-to-send-basic-auth-with-axios](https://stackoverflow.com/questions/44072750/how-to-send-basic-auth-with-axios)

**Comment by jhmullen** [comment]
This was added: https://github.com/Datawheel/canon/tree/master/packages/cms#environment-variables
