### ISSUE TITLE
[cms] hook up quick rename of slug and title in Section Editor

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#575]
@perpetualgrimace added quick-edit pen buttons for titles. Add the functionality for these.

**Comment by perpetualgrimace** [comment]
The Header component has two props set up as click handlers for this: `onRenameTitle`
and `onRenameSlug`

**Comment by jhmullen** [comment]
Since the horizontal nav change, the header no longer exists in this form. Closing this issue.
