### ISSUE TITLE
[cms] Style login panel and logout link

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#590]
This commit adds a login wall to the cms:  https://github.com/Datawheel/canon/commit/2609d7cd3de82deb506e8b873602e63508f61da7

In the `issue-584-auth` branch, can you please:

- [x] Style the LoginSignup.jsx panel to match the CMS (In Codelife, I remember you somehow might have mirrored/remade the canon-core login/signups? I'm currently directly importing them from core)
- [x] Choose where to place the "logout" link (I currently put it in settings)
- [x] Style the "Contact administrator" state from when the user has insufficient permissions.

**Notes on how to test this:**

You should be able to do your normal "force this state to be true for testing purposes" logic in lines 115-125 of Builder.jsx.  However, to actually test the functionality here:

- Set `CANON_LOGINS=true` in your env.
- You should then get kicked out to Login/Signup.  Make an account
- Notice that your new Signup has insufficient privs, so it should show the "Contact Admin"
- Go into Postico, in your `users` table, find yourself, change your `role` from 0 to 1, notice that you now have access
- Test the log out button functionality, which should kick you back to the login wall.

**Comment by davelandry** [comment]
great write-up @jhmullen 👍 

@perpetualgrimace you also have my complete blessing to just make changes to the core Login components being used here (without removing any features/functionality, grab me if you have any questions). They should all be in here: https://github.com/Datawheel/canon/tree/master/src/components
