### ISSUE TITLE
[core] update postcss-custom-properties when changing style.yml

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#592]
Currently, if I make any changes to style.yml, I need to clear the cache and rerun the build in order to see those changes.

**Comment by davelandry** [comment]
let's call it like it is, a **BUG** 🐛

**Comment by perpetualgrimace** [comment]
Ahaha. I err on the side of not calling things bugs if there's any potential case to be made that they should be called something else 😆
