### ISSUE TITLE
[vizbuilder] adding a second drilldown to a cube with a different required drilldown results in an error

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#612]
That's my hunch, take a look at this build: http://localhost:3300/visualize?groups=0-1cCiqp&measure=ZjsmSE

If you add a second grouping for "Language Spoken at Home", the resulting mondrian query includes a "Nation" drilldown where it should be "State". My guess is that the `is_required` dim is overriding "State" in this case?

**Comment by davelandry** [comment]
Turns out it only happens if you have selected to cut by a state. Steps to reproduce:
1. visit https://datausa.io/visualize?enlarged=c-lineplot-yiXGF-04000US06&groups=0-yiXGF-04000US06&measure=ZJtXqi
2. Press "Add grouping"
3. "Apply" the grouping of "Language Spoken at Home"
4. Error ssays "No data available at that granularity."
5. Mondrian-rest data URL seems to have a Nation drilldown: https://flint-api.datausa.io/cubes/acs_ygl_language_spoken_at_home_by_english_ability_2016_5/aggregate.jsonrecords?drilldown%5B%5D=%5BLanguage+Spoken+at+Home%5D.%5BLanguage+Spoken+at+Home%5D&drilldown%5B%5D=%5BYear%5D.%5BYear%5D&drilldown%5B%5D=%5BGeography%5D.%5BNation%5D.%5BNation%5D&cut%5B%5D=%5BGeography%5D.%5BState%5D.%5BState%5D.%26%5B04000US06%5D&measures%5B%5D=Languages+Spoken&nonempty=true&distinct=false&parents=false&debug=false&sparse=true

**Comment by perpetualgrimace** [comment]
![36unrm](https://user-images.githubusercontent.com/6193798/62143211-97643280-b2bd-11e9-8816-5cd22281cf4e.jpg)

**Comment by frabarz** [comment]
found it
it was caused by a residue of an old functionality we later removed, this should fix it
