### ISSUE TITLE
[cms] allow viz option buttons to be disabled or enabled via visualization editor

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#620]
Sometimes content authors may choose not to display the buttons above the viz. We should provide options for disabling them in the cms.

I suggested using the config for this, but Dave is concerned about overloading d3plus configs with canon props. So this will look more like adding checkboxes for each option to the visualization editor, and adjusting the database accordingly.

Background:
https://datawheel.slack.com/archives/C6D91RL4B/p1564497528030000

**Comment by perpetualgrimace** [comment]
Did some work on a [620-disable-viz-options](https://github.com/Datawheel/canon/tree/620-disable-viz-options) branch. Theoretically if we add an `optionsVisible` boolean to the visualization table and set it to `false`, the options will be hidden.

**Comment by jhmullen** [comment]
@davelandry Annie had requested the ability to hide/disable each of the three Options buttons.

The last time this was discussed, as you can see above, you didn't want to overload the d3plus config with extra cms-type stuff, instead opting to create a new column/config for the visualization in the database itself with a checkbox in the UI.

Is that still your contention, or can I approach this issue with some kind of `optionsConfig` array inside the d3plus config? This would be my preferred option.

**Comment by davelandry** [comment]
@jhmullen my gut tells me this should be profile-level, not viz-level. Did Annie (or anyone else) really want to disable these things per viz? If so, then I would prefer for us to have these viz options in a separate column/UI, as to not override the config itself (and move the other secret things like "tabs" to there as well)

**Comment by jhmullen** [comment]
@davelandry It was per-viz, due to anonymized data (hiding the Download button).

I tend to agree, let's do it right and keep d3plus pure.

Closing this, in lieu of the newly created #1216
