### ISSUE TITLE
[vizbuilder] new "BUCKET" visualization types

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#622]
Depended on https://github.com/Datawheel/datausa-tracker/issues/259

When adding "bucket/bin" type of drilldown, (like [Age](http://datausa.io/visualize?groups=0-19hV1x-271020&groups=1-1zewFP&measure=1qWfo) or [Wages](http://datausa.io/visualize?groups=0-19hV1x-271020&groups=1-ZQl9sQ&measure=1qWfo)), you are currently presented with a Tree Map, Line Plot, and Stacked:

<img width="917" alt="Screen Shot 2019-07-30 at 1 55 04 PM" src="https://user-images.githubusercontent.com/1847581/62153003-a9e86700-b2d1-11e9-88f1-d19ed8a04f2e.png">

We will be adding a `dim_type: "BUCKET"` to those dimensions, and if that `dim_type` is present, I would expect to see the following non-aggregate charts instead of what is already being shown:
- [ ] barchart/distribution with the bucket dimension on the x-axis
- [ ] lineplot with the bucket dimension on the x-axis

Additionally, we will also need to sort the axis by the ID of the bucket, so for example:
```js
config.xSort = (a, b) => a["ID Age"] - b["ID Age"]
```

**Comment by jhmullen** [comment]
@frabarz Is this still active?
