### ISSUE TITLE
[cms] implement flickr image management

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#636]
Current Data USA google sheet: https://docs.google.com/spreadsheets/d/1emEA-Tz4EBugidBRSQ5e4eq9AkQaEqAerTW0XtGL4AI/edit#gid=1064521817

And node script: https://github.com/DataUSA/datausa-site/blob/staging/scripts/flickr-scrape.js

**Comment by davelandry** [comment]
I'm adding to @perpetualgrimace to this issue to add in the CSS next week.

**Comment by davelandry** [comment]
@perpetualgrimace `feature-multisearch` branch

**Comment by davelandry** [comment]
(you may need to wait for Jimmy to get back in on Thursday to help with any db changes)

**Comment by jhmullen** [comment]
@davelandry I had set up @perpetualgrimace last week with a working DB so he is good to go here.

**Comment by perpetualgrimace** [comment]
Related bug: #690
