### ISSUE TITLE
[cms] show preview name in dimension search

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#642]
I've seen a few people (myself included) get confused when trying to change the preview dimension. The input box is labeled as "preview ID" and shows the ID, but you cannot search by ID (only by name).

Maybe separate "preview ID" out to it's own separate line and display the name in the search box?

**Comment by perpetualgrimace** [comment]
let's talk about this in person at some point, because the reason it's probably confusing is because I'm also confused about it 😅

**Comment by perpetualgrimace** [comment]
@jhmullen accidentally started working on this 😁

**Comment by davelandry** [comment]
@jhmullen this is resolved with #703, right?

**Comment by jhmullen** [comment]
@davelandry Yes this will be resolved by #703
