### ISSUE TITLE
[cms] no way to remove a sticky section without rendering sticky section

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#651]
Currently, if I want a sticky section to disappear after a few sections, I need to render another subsequent sticky section on top of it. Our initial idea is that if you put in an empty sticky section it will push the previous one out... but then we found out that it only goes on top of the previous one.

I have a 2 step solution to this, tell me what you think:
1. manage the sticky sections at the top profile level, and set a "hidden" class on any ones previous to the current sticky (and make that class slide the section off the top of the page)
2. when adding a sticky section to the CMS, if it has no contents to render reduce the styles to be invisible

**Comment by perpetualgrimace** [comment]
if a sticky section is in a grouping, and you hit a new grouping, it will slide off the top of the page

**Comment by davelandry** [comment]
@perpetualgrimace not from what I can see: https://cdc-earwig.datawheel.us/profile/geography/32

**Comment by davelandry** [comment]
@perpetualgrimace (I'm fixing the extra margin and padding and z-index right now)

**Comment by perpetualgrimace** [comment]
ahhhh, that's because cdc is using a super hacky custom Profile that doesn't have the grouping logic that the canon Profile has 😅

**Comment by davelandry** [comment]
@perpetualgrimace ahhhh gotcha, I can grab that then. Continue on with OEC
