### ISSUE TITLE
[vizbuilder] measure select with search query jumps to top on scroll

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#660]
This needs to be fixed on v0.2 and v0.3 😢 

https://datausa.io/visualize?groups=0-14F1wI&measure=1wObYo

![scroll](https://user-images.githubusercontent.com/1847581/63369933-1265b980-c34f-11e9-9fe6-03a3e4fa60f1.gif)

**Comment by frabarz** [comment]
the fix for this was included in e36d28979b37dd2dd918295aa37afc797de9ab99, for v0.4
