### ISSUE TITLE
[vizbuilder] filter measure list names overlap

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#661]
Another one for v0.2 and v0.3:

https://data.authorityhealth.org/charts?enlarged=c-geomap-Z1NrQxQ&groups=0-Z1NrQxQ&measure=1zIGWs

<img width="294" alt="Screen Shot 2019-08-20 at 1 34 41 PM" src="https://user-images.githubusercontent.com/1847581/63370043-522ca100-c34f-11e9-8e9d-08d91e92c975.png">

**Comment by frabarz** [comment]
the fix for this was included in e36d28979b37dd2dd918295aa37afc797de9ab99, for v0.4
