### ISSUE TITLE
[core] upgrade/replace react-router

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#672]
Since recent canon updates I've been getting this warning after running the build:

```
69% building 2240/2270 modules 30 activeWarning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: RouterContext
```

**Comment by davelandry** [comment]
Upgrading react-router would resolve this, but that would require a major canon release and all of our sites to adopt the newest (very different) react-router syntax.

My gut tells me that we should roll our own router, and try to preserve as much of the current syntax as possible in order to not disrupt the sites that use canon.

**Comment by davelandry** [comment]
In the meantime, I've locked canon-core v0.17.57 to React v16.8.0 in order to surpress these (somewhat annoying) warnings.

**Comment by jhmullen** [comment]
Updating react-router will be part of 1.0/canon-reports. Closing this

**Comment by davelandry** [comment]
@jhmullen didn't we say that since this is a `core` issue, it isn't part of canon-reports? is this issue getting tracked anywhere else?

**Comment by jhmullen** [comment]
Yes, thanks for the correct. Tracked now at #1325
