### ISSUE TITLE
[cms] share links do not work

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#681]
For example: https://cdc-earwig.datawheel.us/profile/geography/33#changes-over-time-sir

The share link that is shown in the pop-up is this: https://cdc-earwig.datawheel.us/profile/geography/33#changes-over-time-sir-0

Which leads nowhere...

**Comment by perpetualgrimace** [comment]
That's really weird!

Here's the line where the faulty part of the link is constructed:
https://github.com/Datawheel/canon/blob/a9780cac110d4e3dd7ecf7e44e41f48d013d41ef/packages/cms/src/components/Viz/Options.jsx#L257

Could this be an issue where an incorrect slug is being passed in from the CMS?

**Comment by davelandry** [comment]
@jhmullen?
