### ISSUE TITLE
[cms] left-align sibling selector dropdown options

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#682]
For example, in this CDC screenshot:
![image-20190906-000505](https://user-images.githubusercontent.com/1847581/64558370-b10f8580-d311-11e9-9ad5-f29d24c5b4e6.png)

**Comment by perpetualgrimace** [comment]
Shouldn't this be a CDC thing, not a canon thing? Inline selectors are very space efficient, and can easily be overridden on a project basis if needed. 🤔

**Comment by davelandry** [comment]
😘 https://github.com/DeloitteGeospatial/cdc-pha/issues/986
