### ISSUE TITLE
[cms] do not truncate inline selectors

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#684]
![image-20190906-182640](https://user-images.githubusercontent.com/1847581/64558954-229c0380-d313-11e9-81e6-adb1257aa9a6.png)

**Comment by perpetualgrimace** [comment]
I think this is more of a CDC thing than a canon thing. Selectors are auto width by default, these guys have been hacked into place.

**Comment by davelandry** [comment]
K: https://github.com/DeloitteGeospatial/cdc-pha/issues/985
