### ISSUE TITLE
[cms] Infographic viz type

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#694]
Similar to ProgressBar, we have the need for a new (fairly simple) viz type that is basically:

```js
return {
  image: "static-url-to-image.jpg",
  subtitle: "Less than 8 blocks from", //optional
  title: "Public Transit", // optional
  value: "94.2%" // optional
}
```

https://es.datachile.io/geo/los-lagos-10/puerto-montt-233#environment

<img width="1618" alt="Screen Shot 2019-09-16 at 8 28 07 AM" src="https://user-images.githubusercontent.com/1847581/64958080-48b62c00-d85c-11e9-9af4-37dd3579c231.png">

**Comment by perpetualgrimace** [comment]
@davelandry I more or less have this set up, but the Tabs section layout groups them together (as expected):

![graphic-viz-in-tabs](https://user-images.githubusercontent.com/6193798/65799180-75622180-e141-11e9-83bb-2caa7b54f8a5.gif)

**Comment by davelandry** [comment]
@perpetualgrimace yeah that's expected behavior IMO. If you wanted them to all be in the same tab, you can add `tab: "My Tab Title"` to the viz config and it should group them based on that title.

**Comment by perpetualgrimace** [comment]
Thought so! Okay, I've made a [PR](https://github.com/Datawheel/canon/pull/728). It fixes a bug and closes another issue as well so it'd be good to release it when possible!
