### ISSUE TITLE
[cms] allow visualizations to edit state

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#695]
Open for discussion, but my initial though is: what if we (somehow) provided the `setState` function to viz configs, and that would allow them to set custom properties on state.

For example, an click event in a Treemap:
```js
on: {
  click: d => setState({highlight: d.id})
}
```

And then, if they desire, other visualizations can access this value to change their contents:

```js
data: state.highlight ? `custom-url-${state.highlight}` : "default-url"
```

**Comment by jhmullen** [comment]
To clarify, is this true access to React State? i.e., the viz can break out of its container and write to the JSX state?  Or, is this simply a similarly-named method that behaves like a selector, in that it injects the state  "lookup" object into all future varswaps, and can be passed around via url params if necessary?

I think we discussed that it is the latter, but just marking here for posterity.

**Comment by davelandry** [comment]
@jhmullen I don't think it necessarily needs to be "true" react state, so let's avoid that to keep the implementation more self-container?
