### ISSUE TITLE
[cms] permalinks for story and metadata editors

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#702]
**Motivation:**
As we add more pages to the CMS, navigating between them becomes a pain. I've already found myself wishing I could cmd-click the profile editor button to open it in a new tab while I'm in the metadata editor page, and vice-versa.

Not sure how difficult it would be to create linkable "routes" to these three pages without creating `Routes`, if you know what I mean.

**Comment by davelandry** [comment]
@perpetualgrimace do you mean just permalinks for the story and metadata editors, similar to how we have permalinks for the specific Section you're currently editing?

**Comment by perpetualgrimace** [comment]
well currently the permalink structure is like:
`/?profile=1&section=1`

It'd be nice if it was like:
`/profile/1?section=1`
`/story/1`
`/meta`

**Comment by davelandry** [comment]
Without adding new routes, it'll have to be something like this:

`/?tab=profile&profile=1&section=1`
`/?tab=story&story=1`
