### ISSUE TITLE
[cms] add ES6 support for formatters

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#710]

**Comment by davelandry** [comment]
@cnavarreteliz formatters should have ES6 support... can you post an example of code that is not working for you?

**Comment by jhmullen** [comment]
@davelandry I asked him to open this, fat-arrow functions were not working. I think it has to do with d3plus-propify, but it will require more research on my part.

**Comment by jhmullen** [comment]
I just tested this and es6 is working fine. Not sure what the circumstances of the original situation were, but closing this issue.
