### ISSUE TITLE
[core] make mixins available to all css files via webpack

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#713]
related:
- https://github.com/Datawheel/canon/issues/124
- https://github.com/Datawheel/canon/issues/41

**Comment by davelandry** [comment]
@perpetualgrimace what's your current import statement that you have to make?

**Comment by perpetualgrimace** [comment]
So what I've done for OEC is, create a project `mixins.css` file in the `/helpers` directory, then import canon mixins at the top:
`@import "../node_modules/@datawheel/canon-cms/src/css/mixins.css";`

I think need to import the project mixins file at the top of every project css file:
`@import "../helpers/mixins.css";`

**Comment by davelandry** [comment]
ahh got it, yeah we should figure out a better way to make this work.

as a sidenote, does this simpler import statement work?
```css
@import "@datawheel/canon-cms/src/css/mixins.css";
```

**Comment by perpetualgrimace** [comment]
maybe, let me try it!

**Comment by perpetualgrimace** [comment]
Seems to work.
