### ISSUE TITLE
[cms] viz ui-mode doesn't work with APIs without "data" accessor

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#720]
**motivation**
Last night I was a dumb dumb and thought I broke the cms, but it turns out I was just using an API that doesn't return an axios-style `.data` accessor. It'd be nice if we could use any old API to generate visualizations in the future.

(In the meantime, I will remember to use `/api/test` 😅)

**Comment by davelandry** [comment]
@perpetualgrimace what does the API that you were using return? just an Array of objects?

FYI: axios isn't the thing that defines the "data" accessor, that's defined by the API creator

**Comment by perpetualgrimace** [comment]
An array of objects, yes. This is what I was attempting to use:
https://jsonplaceholder.typicode.com/posts
