### ISSUE TITLE
[cms] card formatting with leaking html

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/canon#721]
Take a look at this preview from a card in the cms, somehow there are `nbsp;` html entities coming through.

<img width="749" alt="Screen Shot 2019-09-27 at 11 34 04 AM" src="https://user-images.githubusercontent.com/252276/65782076-eb9f5d80-e11a-11e9-9635-e86db2a8677c.png">

**Comment by perpetualgrimace** [comment]
related?
https://datawheel.slack.com/archives/C6D91RL4B/p1564072235020800

**Comment by perpetualgrimace** [comment]
Ohhh, this is only for the card preview. @alexandersimoes Are they printing as entities or characters on the profile?

**Comment by alexandersimoes** [comment]
Yup it's related. They print out properly on the front-end of the site,
it's just the preview that is weird.
