### ISSUE TITLE
[cms] horizontal Sketch redesign of profile tree navigation

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#725]

**Comment by davelandry** [comment]
Sketch design is approved for implementation! (#726)

@perpetualgrimace can you post a screenshot of the design here for posterity?

**Comment by perpetualgrimace** [comment]
![cms-panel-horizontal-nav-mockup_v2 3-columns@2x](https://user-images.githubusercontent.com/6193798/66325302-029d3700-e8f5-11e9-90a8-94b87be2299f.png)
