### ISSUE TITLE
'vips/vips8' file not found

### ISSUE THREAD

**Issue by rhauckdot** [Datawheel/canon#734]
I can't install canon-cms@0.8.11 because I run into the following error when it installs the `sharp` dependency:

```
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
```
This issue was recently documented here: 
https://github.com/lovell/sharp/issues/1882

**Comment by davelandry** [comment]
@rhauckdot we're unable to fix this on our end, as this is a deeply nested dependency within Sharp (type `npm ls minipass` to see the dependency tree).

Reading that thread, there was an update to minipass put out a few days ago that fixes this, so I would:
* update node and npm to their latest versions on your local machine
* run `npm ci` on your package
* try to upgrade to the latest canon-cms again
