### ISSUE TITLE
[cms] incorrect "view data" url in modal sections

### ISSUE THREAD

**Issue by cnavarreteliz** [Datawheel/canon#736]
In this moment, the URL shared in View Data section, includes reserved words like `<hierarchy>=<id>`

![image](https://user-images.githubusercontent.com/5233593/66132839-12064280-e5cc-11e9-9850-8e35124f81c4.png)

**Comment by jhmullen** [comment]
@cnavarreteliz has indicated to me that this was user error hard-coding an incorrect URL, and to close this issue.
