### ISSUE TITLE
[core] don't use compiled/SSR style.css in dev mode

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#738]
**Motivation**: Canon spits out a single pre-processed/minified style.css file for production, which is good™. When adding new styles, this is typically fine, since the newly injected styles will overwrite the prebuilt SSR styles. 

But when *removing* styles, the prebuilt styles remain despite having been deleted in the css partial they came from. These ghost styles can be confusing/annoying, and they persist until the build is re-run.

It also means the inspector styles panel is clogged up with duplicate styles.

Possible to skip the compiled styles in dev, and only include them in production?

**Comment by jhmullen** [comment]
@davelandry is this still active?

**Comment by davelandry** [comment]
`dev` mode now has NO compiled server CSS, resulting in that ugly FOUT but solving this problem 👍🏻
