### ISSUE TITLE
[cms] unable to save viz-only PercentageBar

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#748]

**Comment by perpetualgrimace** [comment]
I'm not seeing this behavior. Any other details on how to reproduce?

**Comment by davelandry** [comment]
@perpetualgrimace I'll loop back with Andrew and let you know what he says 👍

**Comment by davelandry** [comment]
@perpetualgrimace I did some digging and found the following:
1. it's not an IE bug, it happens in Chrome/macOS too
2. it's only related to the PercentageBar viz type, but might also effect the other React viz types (Table and Graphic)
3. when trying to save the "visualization only", the Options component chokes when trying to find the new DOM node [here](https://github.com/Datawheel/canon/blob/master/packages/cms/src/components/Viz/Options.jsx#L121)

For some reason that PercentageBar component object doesn't appear to be "mounted", which results in `_renderedComponent` being undefined. I fiddled with different ways of using `ref` in React, but am chucking it back to you for help!

**Comment by perpetualgrimace** [comment]
Yikes. I'm also fuzzy on the ref stuff (and the Options logic in general) but I'll see if I can figure it out.

**Comment by perpetualgrimace** [comment]
Okay I've mostly gotten this working, tested with d3plus visualizations, custom visualizations, and sections. It seems that I'm passing the correct node in each case and we're not crashing any more. 

My main issue now is that when I choose to save the entire section, the section text isn't rendered in the png, it's just white space. This is true whether I set the background to transparent or not. 😕

Any ideas?

**Comment by davelandry** [comment]
Hmm, might be related to #746 

The CDC guys noticed that selectors were not appearing in downloads anymore either. My hunch was that there was some styling property that has changed, and that's causing the image module to not know how to render a specific property (like "absolute" with weird margins, like what we now do with the title anchor links).

If you can help me figure out if a CSS property is causing this, I can catch for this in the image renderer we use from d3plus-export.
