### ISSUE TITLE
[cms] handle multiple URLs in view data popup

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#768]
It's not possible for a viz config `data` to be an _Array_ or URLs (and not just a single _String_). If this is the case, we should display each URL in a separate line with individual input/copy controls.

The returned data is still expected to compile down to 1 array of data, so this should effect the displayed table (but might effect the axios calls to get the data)

**Comment by perpetualgrimace** [comment]
<img width="682" alt="Screen Shot 2019-10-17 at 4 47 41 PM" src="https://user-images.githubusercontent.com/6193798/67046524-64804c80-f0fe-11e9-9a71-953405c4fe83.png">

😁
