### ISSUE TITLE
[cms] re-enable Tabs section viz-defined selectors

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#769]
At some point, the Tabs section allowed visualizations to specify which selectors should be shown with the given visualization. Something akin to:

```js
const vizConfig = {
  ...,
  selectors: ["year-select", "hai-select"]
};
```

```jsx
const mySelectors = vizConfig.selectors ? selectors.filter(s => vizConfig.selectors.includes(s.slug)) : selectors;
```

That's just pseudo-code, let me know if you want to talk this through.

**Comment by perpetualgrimace** [comment]
Got it. Not all filters will necessarily make sense for all tabs/visualizations.

**Comment by perpetualgrimace** [comment]
Man, feel like I'm close, but as soon as I activate selectors on a tab section, the page errors out:
`"TypeError: Cannot read property 'split' of undefined at new Selector`

**Comment by perpetualgrimace** [comment]
Okay we're in business. For some reason, this was a bug that required a rebuild.

![selector-selections](https://user-images.githubusercontent.com/6193798/67328182-1943b080-f4e7-11e9-9cf3-e1a8a9369f9a.gif)
