### ISSUE TITLE
[cms] pinned sections for logged in users

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#779]
**Motivation**: Corporate users tend to be interested in a few visualizations/sections, and will want to quickly get to those, while deemphasizing the information they're not concerned with.

Brought up by Cata in 10/17 CMS meeting.

**Comment by jhmullen** [comment]
This is a good thing to revisit for post 1.0 - marking as inactive for now.

**Comment by jhmullen** [comment]
Closing for #1231
