### ISSUE TITLE
[cms] Better formatting of numbers disguised as strings in table viz

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#782]
From Alex: "Your column formatting checks if the users values are number and if so calls the abbreviate function, the only problem is that the payload i'm getting from tesseract returns strings (this is a known issue that has to do with nullable types in tesseract). For this reason the isNan() function was telling the column formatter the value was a number but then the abbrevate function chokes when it tries to format it"

**Comment by davelandry** [comment]
@perpetualgrimace are you using a custom abbreviate function? the d3plus-format `formatAbbreviate` function should correctly abbreviate string values that can be converted to numbers.

If you are using a custom abbreviate function, I'm open to incorporating any improvements directly into d3plus-format!

**Comment by perpetualgrimace** [comment]
We're using this one:
https://github.com/Datawheel/canon/blob/master/packages/cms/src/utils/formatters/abbreviate.js

**Comment by davelandry** [comment]
Ahh cool. Can you make that a pass-through for `formatAbbreviate` from d3plus-format? It's essentially the centralized (and improved upon) version of that function: https://github.com/d3plus/d3plus-format/blob/master/src/abbreviate.js#L44

Should just be something like `module-exports = formatAbbreviate;` after you require it.

**Comment by perpetualgrimace** [comment]
@davelandry turns out, what we did broke the abbreviate formatter for CMS users. Thanks to @jhmullen for helping me unbreak it. 🙏
