### ISSUE TITLE
[cms] Materializers won't load in unless there is at least one Generator

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#786]
Before 1st generator:
<img width="420" alt="Screen Shot 2019-10-21 at 1 09 41 PM" src="https://user-images.githubusercontent.com/6193798/67226941-276cd080-f404-11e9-811d-c8e073f23359.png">

After 1st generator:
<img width="408" alt="Screen Shot 2019-10-21 at 1 09 51 PM" src="https://user-images.githubusercontent.com/6193798/67226948-2c318480-f404-11e9-9229-47016494a058.png">

**Comment by jhmullen** [comment]
Note to self: generators don't work unless there's one materializer too

**Comment by jhmullen** [comment]
This is fixed in a0bee70043ac72d91106994dccf196779e8d5b76 and will be closed when `refactor-redux` is merged.
