### ISSUE TITLE
[cms] fix 413 entity too large error

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#787]
* go to this progressbar viz: https://cdc-earwig.datawheel.us/profile/geography/31#sir
* open your console
* and change the first selector ("hai type")

```
app.js:34437 POST https://cdc-earwig.datawheel.us/api/profile?profile=5&hai-select-sir=haiCAUTI 413 (Request Entity Too Large)
app.js:34437 Uncaught (in promise) Error: Request failed with status code 413
```

**Comment by jhmullen** [comment]
This was solved by increasing the ngnix upload size as specified [here](https://www.keycdn.com/support/413-request-entity-too-large).
