### ISSUE TITLE
[cms] port lunr search from Data USA

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#790]
Should be pretty simple, there's 2 main parts to this:
1. create a search index in `cache/` on boot: https://github.com/DataUSA/datausa-site/blob/master/cache/searchIndex.js
2. use the new search index in the API route: https://github.com/DataUSA/datausa-site/blob/master/api/searchRoute.js#L37-L66

**Comment by jhmullen** [comment]
Putting this on hold for now pending more DeepSearch work - however my work is preserved on the `issue-790-lunr` branch.

**Comment by davelandry** [comment]
closing in favor of #875
