### ISSUE TITLE
[cms] allow stats to layout nicely regardless of whether they are grouped

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#805]

**Comment by davelandry** [comment]
@perpetualgrimace what did you have in mind for this one?

**Comment by perpetualgrimace** [comment]
Basically making better use of flex-basis, to allow stat groups to span 2-3 "columns" depending on how many stats they have, and rendering single stats without wrappers as single "columns". It's roughly there, I just want to do a bit more testing to make sure it holds up in different arrangements of stats.
