### ISSUE TITLE
[cms] return error message with invalid slug/id combinations for profiles and stories

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#807]
Currently, the endpoints completely hang (and eventually timeout) if a user asks for an invalid profile slug/id or story id. 

Can we make these endpoints return some sort of error payload so that the front-end devs can decide how to handle that?

We'll also want to make sure that the default Profile and Story react components fail gracefully.

**Comment by jhmullen** [comment]
@davelandry Can this be closed, due to cfe7ab6200141d215abd5248c860a188a7f43837 ?
