### ISSUE TITLE
[cms] profile sub-nav component

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#816]

**Comment by perpetualgrimace** [comment]
Database changes needed (for each section title object):
- Section short title (optional; overrides section title in subnav if set)
- Icon (optional; displayed next to subnav section title)

**Comment by perpetualgrimace** [comment]
Perhaps if the icon is prefixed by `blueprint-`, then we use the blueprint icon? And otherwise, we'll assume icons are in a predetermined directory? `static/images/icons`?

**Comment by davelandry** [comment]
Hmm, I'm torn about how much we should support Blueprint natively. If we wanted to do the prefix thing, then I would say let's whip up a little icon chooser and have a like a `isBlueprint` toggle that goes in between that and an input box for a static URL...

...or we just do an input box and require users to link to valid URLs ¯\_(ツ)_/¯

...or if we wanted the most forward thinking solution, why not only make this feature available for CMS users that have a google cloud bucket enabled for profile images, and we give them a little "upload your icon here" interface that stores it in google cloud 🤤

**Comment by perpetualgrimace** [comment]
Mmmm, google cloud. 🤤

I like this, because it means we can limit & compress the image size.

But what about inline SVG??? It's nice to be able to tweak those fill & stroke properties via css, which is only possible if we inline an SVG icon. 🤔

**Comment by davelandry** [comment]
If the user uploads an SVG, is there any way we can convert that into inline code?

**Comment by perpetualgrimace** [comment]
Inlining SVGs in react is one of those things that is more difficult than it should be.

For OSC, I used [react-inlinesvg](https://github.com/gilbarbara/react-inlinesvg), since it meant I didn't have to mess with webpack, but I remember running into some issues with it.

Although I'm reading that we might be able to just use our good friend `dangerouslySetInnerHTML`. I'll look into this further.
