### ISSUE TITLE
[cms] add `contentId` to sequence reset in migration scripts

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#818]
`contentId` needs to have its sequence head reset as part of a migration.

**Comment by davelandry** [comment]
@jhmullen should we do `contentId` explicitly, or something more generic like `/[A-z]Id/g`?

**Comment by jhmullen** [comment]
I would want to triple check that resetting a sequence has no ill effects on non-sequence columns - if that is the case then it should be okay to do an `id` match.
