### ISSUE TITLE
single grouping section has incorrect background color

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#822]
when creating a new profile with only 1 grouping section, it looks like the default text for the title is white on a white background:

<img width="1262" alt="Screen Shot 2019-11-19 at 3 00 40 PM" src="https://user-images.githubusercontent.com/1847581/69181616-6793a180-0add-11ea-9ac7-f378718341ef.png">

**Comment by perpetualgrimace** [comment]
![giphy](https://user-images.githubusercontent.com/6193798/69083766-c9d2a080-0a10-11ea-9714-464cbcb15c79.gif)

**Comment by davelandry** [comment]
Happened using a stock cms install, creating a new "Section" type and adding a section within it.
