### ISSUE TITLE
[cms] strictly enforce hero section as first section

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#850]

**Comment by perpetualgrimace** [comment]
And the award for vaguest issue goes to... 🏆😅

**Comment by jhmullen** [comment]
@perpetualgrimace To give you some context here:

The Hero stat is currently a dropdown option, but only if the section is the first in the profile.  This leads a problem we have encountered where a user has their first Hero section, and they (accidentally or otherwise) move it further down the page.  This hides the Hero option from the drop-down, so it LOOKS like it's a default section, but in the actual DB it's a Hero type.

Further, the code for how hero types work doesn't even check for ordering -- Hero.jsx does a `.find` operation and grabs a hero from WHEREVER it is in the list, first or otherwise. This means that the buried hero (from the earlier example) is still confusingly grabbed, and promoted to Hero status.

More generally the relationship between Profile and Hero is muddled as well.  The first thing a user might do in the CMS at all is set the title of their profile to `{{name}}` or `State Profile` or something like this. However, Hero.jsx only falls back upon the Profile title if Hero doesn't exist at all. Because we automatically create a Hero section upon profile creation, The user would never even see their profile title unless they manually changed the type of the 1st section element from Hero to Default.

Further, because Hero.jsx does a single `.find` operation, it's not even possible to have a "second hero" somewhere down the line, that inserts another "full Hero.jsx blade" (if that were something someone wanted, maybe in a bivariate profile?).  

So my thought here was:

If the Hero type is only available in the first section slot anyway, should we manually enforce a locked Hero section, and hide / obfuscate the ability to set a Profile title at all? The profile Title is only used as a fallback anyway, and Hero sections can't even occur later in a page. @davelandry suggested something along the lines of hiding the profile's (somewhat useless) title entirely, and changing "ProfileEditor.jsx" to include the hard-coded 1st Hero Section, so that it looks like it's doing what you actually _are_ doing: Setting the title / Hero of your entire profile.

Do you have any thoughts on this?

**Comment by jhmullen** [comment]
Hero Section is going away in 1.0
