### ISSUE TITLE
[cms] add preview section modal to section editor

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#871]

**Comment by jhmullen** [comment]
@perpetualgrimace This branch adds a "preview section" button to SectionEditor.jsx

![image](https://user-images.githubusercontent.com/1714292/70828980-858db280-1dba-11ea-927b-0109ee34595d.png)

It adds a new component, PreviewHeader.jsx, which are the settings for the Preview Window:

![image](https://user-images.githubusercontent.com/1714292/70829027-a0602700-1dba-11ea-847a-e5429ea3c7af.png)

This is so the user can change the previews for the section, as well as the language.

Note that the search bars are PreviewSearch.jsx, which is the SAME preview bar that is used by DimensionCard.jsx.

Usage-wise:
- changing the search previews changes the "underlying" search previews too
- changing the locale to a non-default *changes the secondary locale underneath too*
- you have access to `fetchingVariables` and `fetchingSectionPreview` to help the user see the loading progress

Can you design pass this please?

**Comment by perpetualgrimace** [comment]
The hero section doesn't appear to render. 🤔
