### ISSUE TITLE
[cms] weird overlay z-indexing on confirmation messages

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/canon#878]
clicking the delete on a materializer creates the overlay shown below, with all the trashcans and icons on top of the overlay: 
<img width="978" alt="Screen Shot 2019-12-16 at 5 59 03 PM" src="https://user-images.githubusercontent.com/252276/70950195-e7a21e00-202d-11ea-81af-f2df33eae5d0.png">

**Comment by perpetualgrimace** [comment]
ah, my least favorite part of css is back again 😅
