### ISSUE TITLE
[cms] dynamic preview URLs from available routes

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#893]
The logic would be to dig into the `routes` object exported by `router` (seen [here](https://github.com/Datawheel/canon/blob/master/src/CanonProvider.jsx#L176)), and run the following logic:
1. if there is a route available that includes the necessary `slug` and `id` combos, use that
2. otherwise, don't display a link! (it just adds to confusion)

**Comment by jhmullen** [comment]
Once the `issue-875-deepsearch` branch is merged, this will be completed.
