### ISSUE TITLE
Allow onSetVariables to run materializers without destroying state

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#907]

**Comment by davelandry** [comment]
@jhmullen bumping this into the task list for this/next week. I think we're going to need this for the `user.role > 0` logic for variables, right?

**Comment by jhmullen** [comment]
@davelandry This won't be needed for user logic.

I've added a `forceMats` option to the `onSetVariables` function, which runs the materializers with your payload as an input. This is currently only run one time in `ProfileRenderer.jsx`, when the user logs in, so I can manually send the user object to be folded into the payload.  In this singular case, I run materializers using the `forceMats` option, so that all `isPro`-esque materializers can end up as their proper values.

However, using `forceMats` for the general case is destructive - consider the case:

1) User sets `showChart = false` in Materializer A so it has a value in the variables list.  
2) Chart on page calls `setVariables({showChart: true, clickedProduct: "cars"})`;
3) Materializer A runs, setting showChart to false, cancelling the behavior and hiding the chart.

In the future, I need to think of how to handle this general case. For now, it's not necessary for OEC, so we can put this on the back burner.

**Comment by jhmullen** [comment]
Made unnecessary by 1.0
