### ISSUE TITLE
[cms] hide from search results filter in language hints

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#964]
Only needed for `:neighbors` lookup

**Comment by davelandry** [comment]
@jhmullen is this actually still needed, or is it all being handled via the deepsearch API?

**Comment by jhmullen** [comment]
@davelandry The `:neighbors` endpoint doesn't currently know anything about the search table. This would mean I would have to do some "post fetch" pruning on my side - I'm in discussions with Marcio on how we intend to handle it.
