### ISSUE TITLE
[cms] add Microsoft SQL Server support to CMS

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#981]
Sequelize currently makes use of a number of Postgres-only methods and datatypes for the CMS. To expand database support, changes need to be made to accommodate more universal behaviors.

Quicker fixes include:

- [ ] Remove `{returning: true}` from update actions
- [ ] Change `iLike` to `like` for native search
- [ ] Modify uses of `overlap` for detecting `ARRAY` membership (see below)

The more difficult changes involve data types:

- [ ] `profile_meta` uses an `ARRAY` of text to store the list of levels associated with a dimension/cube variant
- [ ] `selector` uses an `ARRAY` of `JSON` to store the options for the selector dropdown
- [ ] `section_visualization` uses `JSON` to store the simple configuration object
- [ ] `generator` uses `JSON` to store the simple configuration object
- [ ] `search_content` uses `JSONB` to store the `attr` lookup, and also an `ARRAY` of text to store keywords

These will need to be simplified to more primitive data types. In the goodest of good-dooby land, these should be normalized out to true database structure with one value per column. Given the time constraints, a `JSON.stringify` type endcode/decode to basic text could cover most of the cases here.

The one aspect which will require more thought would be `search_content` - the `keywords` `ARRAY` uses `overlap` for searching which is fairly performant in PSQL, but will need new consideration if stringified. 

@MarcioPorto - Do any of these changes affect your Deepsearch Ingest? If the above data types were strings, could you JSONify/Arrayify them as part of your import?

**Comment by MarcioPorto** [comment]
@jhmullen the only two columns that I use that would be affected are `attr` and `keywords`. But as long as you're just stringifying them it should be fairly easy for me to just reverse that later 🙂

**Comment by jhmullen** [comment]
I am marking this issue as inactive. A day may come when the courage of postgres fails, when we forsake our tables and break all joins of fellowship, but it is not this day.

**Comment by jhmullen** [comment]
Closing this, we will focus on psql for the near future, and revisit in 1.0 if necessary.
